<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Tree-based methods | Machine Learning for Social Scientists</title>
  <meta name="description" content="Notes, content and exercises for the RECSM 2020 course Machine Learning for Social Scientists." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Tree-based methods | Machine Learning for Social Scientists" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://cimentadaj.github.io/ml_socsci/" />
  
  <meta property="og:description" content="Notes, content and exercises for the RECSM 2020 course Machine Learning for Social Scientists." />
  <meta name="github-repo" content="cimentadaj/ml_socsci" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Tree-based methods | Machine Learning for Social Scientists" />
  
  <meta name="twitter:description" content="Notes, content and exercises for the RECSM 2020 course Machine Learning for Social Scientists." />
  

<meta name="author" content="Jorge Cimentada" />


<meta name="date" content="2020-06-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regularization.html"/>
<link rel="next" href="loss-functions.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.13/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Machine Learning for Social Scientists</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="machine-learning-for-social-scientists.html"><a href="machine-learning-for-social-scientists.html"><i class="fa fa-check"></i><b>1</b> Machine Learning for Social Scientists</a><ul>
<li class="chapter" data-level="1.1" data-path="machine-learning-for-social-scientists.html"><a href="machine-learning-for-social-scientists.html#a-different-way-of-thinking"><i class="fa fa-check"></i><b>1.1</b> A different way of thinking</a></li>
<li class="chapter" data-level="1.2" data-path="machine-learning-for-social-scientists.html"><a href="machine-learning-for-social-scientists.html#split-your-data-into-trainingtesting"><i class="fa fa-check"></i><b>1.2</b> Split your data into training/testing</a></li>
<li class="chapter" data-level="1.3" data-path="machine-learning-for-social-scientists.html"><a href="machine-learning-for-social-scientists.html#cross-validation"><i class="fa fa-check"></i><b>1.3</b> Cross-validation</a></li>
<li class="chapter" data-level="1.4" data-path="machine-learning-for-social-scientists.html"><a href="machine-learning-for-social-scientists.html#bias-variance-tradeoff"><i class="fa fa-check"></i><b>1.4</b> Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="1.5" data-path="machine-learning-for-social-scientists.html"><a href="machine-learning-for-social-scientists.html#an-example"><i class="fa fa-check"></i><b>1.5</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="regularization.html"><a href="regularization.html"><i class="fa fa-check"></i><b>2</b> Regularization</a><ul>
<li class="chapter" data-level="2.1" data-path="regularization.html"><a href="regularization.html#ridge-regularization"><i class="fa fa-check"></i><b>2.1</b> Ridge regularization</a></li>
<li class="chapter" data-level="2.2" data-path="regularization.html"><a href="regularization.html#lasso-regularization"><i class="fa fa-check"></i><b>2.2</b> Lasso regularization</a></li>
<li class="chapter" data-level="2.3" data-path="regularization.html"><a href="regularization.html#elastic-net-regularization"><i class="fa fa-check"></i><b>2.3</b> Elastic Net regularization</a></li>
<li class="chapter" data-level="2.4" data-path="regularization.html"><a href="regularization.html#exercises"><i class="fa fa-check"></i><b>2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tree-based-methods.html"><a href="tree-based-methods.html"><i class="fa fa-check"></i><b>3</b> Tree-based methods</a><ul>
<li class="chapter" data-level="3.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#decision-trees"><i class="fa fa-check"></i><b>3.1</b> Decision trees</a><ul>
<li class="chapter" data-level="3.1.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#advancedsplit"><i class="fa fa-check"></i><b>3.1.1</b> Advanced: how do trees choose where to split?</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#bagging"><i class="fa fa-check"></i><b>3.2</b> Bagging</a></li>
<li class="chapter" data-level="3.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#random-forests"><i class="fa fa-check"></i><b>3.3</b> Random Forests</a></li>
<li class="chapter" data-level="3.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#boosting"><i class="fa fa-check"></i><b>3.4</b> Boosting</a></li>
<li class="chapter" data-level="3.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#exercises-1"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="loss-functions.html"><a href="loss-functions.html"><i class="fa fa-check"></i><b>4</b> Loss functions</a><ul>
<li class="chapter" data-level="4.1" data-path="loss-functions.html"><a href="loss-functions.html#continuous-loss-functions"><i class="fa fa-check"></i><b>4.1</b> Continuous loss functions</a><ul>
<li class="chapter" data-level="4.1.1" data-path="loss-functions.html"><a href="loss-functions.html#root-mean-square-error-rmse"><i class="fa fa-check"></i><b>4.1.1</b> Root Mean Square Error (RMSE)</a></li>
<li class="chapter" data-level="4.1.2" data-path="loss-functions.html"><a href="loss-functions.html#mean-absolute-error"><i class="fa fa-check"></i><b>4.1.2</b> Mean Absolute Error</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="loss-functions.html"><a href="loss-functions.html#binary-loss-functions"><i class="fa fa-check"></i><b>4.2</b> Binary loss functions</a><ul>
<li class="chapter" data-level="4.2.1" data-path="loss-functions.html"><a href="loss-functions.html#confusion-matrices"><i class="fa fa-check"></i><b>4.2.1</b> Confusion Matrices</a></li>
<li class="chapter" data-level="4.2.2" data-path="loss-functions.html"><a href="loss-functions.html#roc-curves-and-area-under-the-curve"><i class="fa fa-check"></i><b>4.2.2</b> ROC Curves and Area Under the Curve</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="unsupervised-methods.html"><a href="unsupervised-methods.html"><i class="fa fa-check"></i><b>5</b> Unsupervised methods</a><ul>
<li class="chapter" data-level="5.1" data-path="unsupervised-methods.html"><a href="unsupervised-methods.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>5.1</b> Principal Component Analysis (PCA)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i><b>6</b> Syllabus</a><ul>
<li class="chapter" data-level="6.1" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i><b>6.1</b> Course description</a></li>
<li class="chapter" data-level="6.2" data-path="syllabus.html"><a href="syllabus.html#schedule"><i class="fa fa-check"></i><b>6.2</b> Schedule</a></li>
<li class="chapter" data-level="6.3" data-path="syllabus.html"><a href="syllabus.html#software"><i class="fa fa-check"></i><b>6.3</b> Software</a></li>
<li class="chapter" data-level="6.4" data-path="syllabus.html"><a href="syllabus.html#prerequisites"><i class="fa fa-check"></i><b>6.4</b> Prerequisites</a></li>
<li class="chapter" data-level="6.5" data-path="syllabus.html"><a href="syllabus.html#about-the-author"><i class="fa fa-check"></i><b>6.5</b> About the author</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Machine Learning for Social Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tree-based-methods" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Tree-based methods</h1>
<p>In this chapter we will touch upon the most popular tree-based methods used in machine learning. Haven’t heard of the term “tree-based methods”? Do not panic. The idea behind tree-based methods is very simple and we’ll explain how they work step by step through the basics. Most of the material on this chapter was built upon <span class="citation">Boehmke and Greenwell (<a href="#ref-boehmke2019" role="doc-biblioref">2019</a>)</span> and <span class="citation">James et al. (<a href="#ref-james2013" role="doc-biblioref">2013</a>)</span>.</p>
<p>Before we begin, let’s load <code>tidyflow</code> and <code>tidymodels</code> and read the data that we’ll be using.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tree-based-methods.html#cb43-1"></a><span class="kw">library</span>(tidymodels)</span>
<span id="cb43-2"><a href="tree-based-methods.html#cb43-2"></a><span class="kw">library</span>(tidyflow)</span>
<span id="cb43-3"><a href="tree-based-methods.html#cb43-3"></a><span class="kw">library</span>(rpart.plot)</span>
<span id="cb43-4"><a href="tree-based-methods.html#cb43-4"></a><span class="kw">library</span>(vip)</span>
<span id="cb43-5"><a href="tree-based-methods.html#cb43-5"></a><span class="kw">library</span>(baguette)</span>
<span id="cb43-6"><a href="tree-based-methods.html#cb43-6"></a></span>
<span id="cb43-7"><a href="tree-based-methods.html#cb43-7"></a>data_link &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/cimentadaj/ml_socsci/master/data/pisa_us_2018.csv&quot;</span></span>
<span id="cb43-8"><a href="tree-based-methods.html#cb43-8"></a>pisa &lt;-<span class="st"> </span><span class="kw">read.csv</span>(data_link)</span></code></pre></div>
<div id="decision-trees" class="section level2">
<h2><span class="header-section-number">3.1</span> Decision trees</h2>
<p>Decision trees are simple models. In fact, they are even simpler than linear models. They require little statistical background and are in fact among the simplest models to communicate to a general audience. In particular, the visualizations used for decision trees are very powerful in conveying information and can even serve as an exploratory avenue for social research.</p>
<p>Throughout this chapter, we’ll be using the PISA data set from the regularization chapter. On this example we’ll be focusing on predicting the <code>math_score</code> of students in the United States, based on the socio economic status of the parents (named <code>HISEI</code> in the data; the higher the <code>HISEI</code> variable, the higher the socio economic status), the father’s education (named <code>FISCED</code> in the data; coded as several categories from 0 to 6 where 6 is high education) and whether the child repeated a grade (named <code>REPEAT</code> in the data). <code>REPEAT</code> is a dummy variable where <code>1</code> means the child repeated a grade and <code>0</code> no repetition.</p>
<p>Decision trees, as their name conveys, are tree-like diagrams. They work by defining <code>yes-or-no</code> rules based on the data and assign the most common value for each respondent within their final branch. The best way to learn about decision trees is by looking at one. Let’s do that:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>In this example the top-most box which says <code>HISEI &lt; 56</code> is the <strong>root node</strong>. This is the most important variable that predicts <code>math_score</code>. Inside the blue box you can see two numbers: <span class="math inline">\(100\%\)</span> which means that the entire sample is present in this <strong>node</strong> and the number <code>474</code>, the average test score for mathematics for the entire sample:</p>
<p>On both sides of the root node (<code>HISEI &lt; 56</code>) there is a <code>yes</code> and a <code>no</code>. Decision trees work by <strong>partitioning</strong> variables into <code>yes-or-no</code> branches. The <code>yes</code> branch satisfies the name of <strong>root</strong> (<code>HISEI &lt; 56</code>) and always branches out to the left:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>In contrast, the <code>no</code> branch always branches out to the right:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The criteria for separating into <code>yes-or-no</code> branches is that respondents must be very similar within branches and very different between branches (later in this chapter I will explain in detail which criteria is used and how). The decision tree figures out that respondents that have an <code>HISEI</code> below <span class="math inline">\(56\)</span> and above <span class="math inline">\(56\)</span> are the most different with respect to the mathematics score. The left branch (where there is a <code>yes</code> in the <strong>root node</strong>) are those which have a <code>HISEI</code> below 56 and the right branch (where there is a <code>no</code>) are those which have a <code>HISEI</code> above <span class="math inline">\(56\)</span>. Let’s call these two groups the low and high SES respectively. If we look at the two boxes that come down from these branches, the low SES branch has an average math score of <span class="math inline">\(446\)</span> while the high SES branch has an average test score of <span class="math inline">\(501\)</span>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>For the sake of simplicity, let’s focus now on the branch of the low SES group (the left branch). The second node coming out of the low SES branch contains 50% of the sample and an average math score of <span class="math inline">\(446\)</span>. This is the node with the rule <code>REPEAT &gt;= 0.5</code>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>This ‘intermediate’ node is called <strong>internal node</strong>. For calculating this <strong>internal node</strong>, the decision tree algorithm limits the entire data set to only those which have low SES (literally, the decision tree does something like <code>pisa[pisa$HISEI &lt; 56, ]</code>) and asks the same question that it did in the <strong>root node</strong>: of all the variables in the model which one separates two branches such that respondents are very similar within the branch but very different between the branches with respect to <code>math_score</code>?</p>
<p>For those with low SES background, this variable is whether the child repeated a grade or not. In particular, those coming from low SES background which repeated a grade, had an average math score of <span class="math inline">\(387\)</span> whereas those who didn’t have an average math score of <span class="math inline">\(456\)</span>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>These two nodes at the bottom are called <strong>leaf nodes</strong> because they are like the ‘leafs of the tree’. <strong>Leaf nodes</strong> are of particular importance because they are the ones that dictate what the final value of <code>math_score</code> will be. Any new data that is predicted with this model will always give an average <code>math_score</code> of <span class="math inline">\(456\)</span> for those of low SES background who didn’t repeat a grade:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Similarly, any respondent from high SES background, with a highly educated father who didn’t repeat a grade, will get assigned a <code>math_score</code> of <span class="math inline">\(527\)</span>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>That is it. That is a decision tree in it’s simplest form. It contains a <strong>root node</strong> and several <strong>internal</strong> and <strong>leaf nodes</strong> and it can be interpreted just as we just did. The right branch of the tree can be summarized with the same interpretation. For example, for high SES respondents, father’s education (<code>FISCED</code>) is more important than <code>REPEAT</code> to separate between math scores:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>This is the case because it comes first in the tree. Substantially, this might be due to the fact that there is higher variation in education credentials for parents of high SES background than for those of low SES background. We can see that those with the highest father’s education (<code>FISCED</code> above <span class="math inline">\(5.5\)</span>), the average math score is <span class="math inline">\(524\)</span> whereas those with father’s education below <span class="math inline">\(5.5\)</span> have a math score of <span class="math inline">\(478\)</span>.</p>
<p>Did you notice that we haven’t interpreted any coefficients? That’s right. Decision trees have no coefficients and many other machine learning algorithms also don’t produce coefficients. Although for the case of decision trees this is because the model produces information in another way (through the visualization of trees), lack of coefficients is common in machine learning models because they are too complex to generate coefficients for single predictors. These models are non-linear, non-parametric in nature, producing very complex relationships that are difficult to summarize as coefficients. Instead, they produce predictions. We’ll be delving into this topic in future sections in detail.</p>
<p>These examples show that decision trees are a great tool for exploratory analysis and I strongly believe they have an inmense potential for exploring interactions in social science research. In case you didn’t notice it, we literally just interpreted an interaction term that social scientists would routinely use in linear models. Without having to worry about statistical significance or plotting marginal effects, social scientists can use decision trees as an exploratory medium to understand interactions in an intuitive way.</p>
<p>You might be asking yourself, how do we fit these models and visualize them? <code>tidyflow</code> and <code>tidymodels</code> have got you covered. For example, for fitting the model from above, we can begin our <code>tidyflow</code>, add a split, a formula and define the decision tree:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tree-based-methods.html#cb44-1"></a><span class="co"># Define the decision tree and tell it the the dependent</span></span>
<span id="cb44-2"><a href="tree-based-methods.html#cb44-2"></a><span class="co"># variable is continuous (&#39;mode&#39; = &#39;regression&#39;)</span></span>
<span id="cb44-3"><a href="tree-based-methods.html#cb44-3"></a>mod1 &lt;-<span class="st"> </span><span class="kw">set_engine</span>(<span class="kw">decision_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>), <span class="st">&quot;rpart&quot;</span>)</span>
<span id="cb44-4"><a href="tree-based-methods.html#cb44-4"></a></span>
<span id="cb44-5"><a href="tree-based-methods.html#cb44-5"></a>tflow &lt;-</span>
<span id="cb44-6"><a href="tree-based-methods.html#cb44-6"></a><span class="st">  </span><span class="co"># Plug the data</span></span>
<span id="cb44-7"><a href="tree-based-methods.html#cb44-7"></a><span class="st">  </span>pisa <span class="op">%&gt;%</span></span>
<span id="cb44-8"><a href="tree-based-methods.html#cb44-8"></a><span class="st">  </span><span class="co"># Begin the tidyflow</span></span>
<span id="cb44-9"><a href="tree-based-methods.html#cb44-9"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">23151</span>) <span class="op">%&gt;%</span></span>
<span id="cb44-10"><a href="tree-based-methods.html#cb44-10"></a><span class="st">  </span><span class="co"># Separate the data into training/testing</span></span>
<span id="cb44-11"><a href="tree-based-methods.html#cb44-11"></a><span class="st">  </span><span class="kw">plug_split</span>(initial_split) <span class="op">%&gt;%</span></span>
<span id="cb44-12"><a href="tree-based-methods.html#cb44-12"></a><span class="st">  </span><span class="co"># Plug the formula</span></span>
<span id="cb44-13"><a href="tree-based-methods.html#cb44-13"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>FISCED <span class="op">+</span><span class="st"> </span>HISEI <span class="op">+</span><span class="st"> </span>REPEAT) <span class="op">%&gt;%</span></span>
<span id="cb44-14"><a href="tree-based-methods.html#cb44-14"></a><span class="st">  </span><span class="co"># Plug the model</span></span>
<span id="cb44-15"><a href="tree-based-methods.html#cb44-15"></a><span class="st">  </span><span class="kw">plug_model</span>(mod1)</span>
<span id="cb44-16"><a href="tree-based-methods.html#cb44-16"></a></span>
<span id="cb44-17"><a href="tree-based-methods.html#cb44-17"></a>vanilla_fit &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb44-18"><a href="tree-based-methods.html#cb44-18"></a>tree &lt;-<span class="st"> </span><span class="kw">pull_tflow_fit</span>(vanilla_fit)<span class="op">$</span>fit</span>
<span id="cb44-19"><a href="tree-based-methods.html#cb44-19"></a><span class="kw">rpart.plot</span>(tree)</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>All <code>plug_*</code> functions serve to build your machine learning workflow and the model <code>decision_tree</code> serves to define the decision tree and all of the arguments. <code>rpart.plot</code> on the other hand, is a function used specifically for plotting decision trees (that is why we loaded the package <code>rpart.plot</code> at the beginning). No need to delve much into this function. It just works if you pass it a decision tree model: that is why <code>pull</code> the model fit before calling it.</p>
<p>I’ve told all the good things about decision trees but they have important disadvantages. There are two that we’ll discuss in this chapter. The first one is that decision trees tend to overfit a lot. Just for the sake of exemplifying this, let’s switch to another example. Let’s say we’re trying to understand which variables are related to whether teachers set goals in the classroom. Substantially, this example might not make a lot of sense, but but let’s follow along just to show how much trees can overfit the data. This variable is named <code>ST102Q01TA</code>. Let’s plug it into our <code>tidyflow</code> and visualize the tree:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="tree-based-methods.html#cb45-1"></a><span class="co">## ST100Q01TA</span></span>
<span id="cb45-2"><a href="tree-based-methods.html#cb45-2"></a><span class="co">## ST102Q01TA</span></span>
<span id="cb45-3"><a href="tree-based-methods.html#cb45-3"></a><span class="co">## IC009Q07NA</span></span>
<span id="cb45-4"><a href="tree-based-methods.html#cb45-4"></a><span class="co">## ST011Q03TA</span></span>
<span id="cb45-5"><a href="tree-based-methods.html#cb45-5"></a><span class="co">## ST011Q05TA</span></span>
<span id="cb45-6"><a href="tree-based-methods.html#cb45-6"></a><span class="co">## ST011Q10TA</span></span>
<span id="cb45-7"><a href="tree-based-methods.html#cb45-7"></a></span>
<span id="cb45-8"><a href="tree-based-methods.html#cb45-8"></a><span class="co"># We can recicle the entire `tflow` from above and just</span></span>
<span id="cb45-9"><a href="tree-based-methods.html#cb45-9"></a><span class="co"># replace the formula:</span></span>
<span id="cb45-10"><a href="tree-based-methods.html#cb45-10"></a>tflow &lt;-</span>
<span id="cb45-11"><a href="tree-based-methods.html#cb45-11"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb45-12"><a href="tree-based-methods.html#cb45-12"></a><span class="st">  </span><span class="kw">replace_formula</span>(ST102Q01TA <span class="op">~</span><span class="st"> </span>.)</span>
<span id="cb45-13"><a href="tree-based-methods.html#cb45-13"></a></span>
<span id="cb45-14"><a href="tree-based-methods.html#cb45-14"></a>fit_complex &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb45-15"><a href="tree-based-methods.html#cb45-15"></a>tree &lt;-<span class="st"> </span><span class="kw">pull_tflow_fit</span>(fit_complex)<span class="op">$</span>fit</span>
<span id="cb45-16"><a href="tree-based-methods.html#cb45-16"></a><span class="kw">rpart.plot</span>(tree)</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The tree is quite big compared to our previous example and makes the interpretation more difficult. However, equally important, some <strong>leaf nodes</strong> are very small. Decision trees can capture a lot of noise and mimic the data very closely. <span class="math inline">\(6\)</span> <strong>leaf nodes</strong> have less than <span class="math inline">\(3\%\)</span> of the sample. These are <strong>leaf nodes</strong> with very weak statistical power:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>What would happen if a tiny <span class="math inline">\(1\%\)</span> of those <strong>leaf nodes</strong> respondend <strong>slightly</strong> different? It is possible we get a complete different tree. Decision trees are not well known for being robust. In fact, it is one of its main weaknesses. However, decision trees have an argument called <code>min_n</code> that force the tree to discard any <strong>node</strong> that has a number of observations below your specified minimum. Let’s run the model above and set the minimum number of observation per <strong>node</strong> to be <span class="math inline">\(200\)</span>:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tree-based-methods.html#cb46-1"></a>dectree &lt;-<span class="st"> </span><span class="kw">update</span>(mod1, <span class="dt">min_n =</span> <span class="dv">200</span>)</span>
<span id="cb46-2"><a href="tree-based-methods.html#cb46-2"></a>tflow &lt;-</span>
<span id="cb46-3"><a href="tree-based-methods.html#cb46-3"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb46-4"><a href="tree-based-methods.html#cb46-4"></a><span class="st">  </span><span class="kw">replace_model</span>(dectree)</span>
<span id="cb46-5"><a href="tree-based-methods.html#cb46-5"></a></span>
<span id="cb46-6"><a href="tree-based-methods.html#cb46-6"></a>fit_complex &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb46-7"><a href="tree-based-methods.html#cb46-7"></a>tree &lt;-<span class="st"> </span><span class="kw">pull_tflow_fit</span>(fit_complex)<span class="op">$</span>fit</span>
<span id="cb46-8"><a href="tree-based-methods.html#cb46-8"></a><span class="kw">rpart.plot</span>(tree)</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The tree was reduced considerably now. There are fewer <strong>leaf nodes</strong> and all nodes have a greater sample size than before.</p>
<p>You might be wondering: what should the minimum sample size be? There is no easy answer for this. The rule of thumb should be relative to your data and research question. In particular, the identification of small nodes should be analyzed with care. Perhaps there <strong>is</strong> a group of outliers that consitute a node and it’s not a problem of statistical noise. By increasing the minimum sample size for each node you would be destroying that statistical finding.</p>
<p>For example, suppose we are studying welfare social expenditure as the dependent variable and then we had other independent variables, among which are country names. Scandinavian countries might group pretty well into a solitary node because they are super powers in welfare spending (these are Denmark, Norway, Sweden and Finland). If we increased the minimum sample size to <span class="math inline">\(10\)</span>, we might group them with Germany and France, which are completely different in substantive terms. The best rule of thumb I can recommend is no other than to study your problem at hand with great care and make decisions accordingly. It might make sense to increase the sample or it might not depending on the research question, the sample size, whether you’re exploring the data or whether you’re interested in predicting on new data.</p>
<p>Despite <code>min_n</code> helping to make the tree more robust, there are still several nodes with low sample sizes. Another way to approach this problem is through the depth of the tree. As can be seen from the previous plot, decision trees can create <strong>leaf nodes</strong> which are very small. In other more complicated scenarios, your tree might get huge. Yes, huge:</p>
<p><img src="img/large_tree.png" width="100%" /></p>
<p>More often that not, these huge trees are just overfitting the data. They are creating very small nodes that capture noise from the data and when you’re predicting on new data, they perform terribly bad. As well as the <code>min_n</code> argument, decision trees have another argument called <code>tree_depth</code>. This argument forces the tree to stop growing if it passes the maximum depth of the tree as measured in nodes. Let’s run our previous example with only a depth of three nodes:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="tree-based-methods.html#cb47-1"></a>dectree &lt;-<span class="st"> </span><span class="kw">update</span>(mod1, <span class="dt">min_n =</span> <span class="dv">200</span>, <span class="dt">tree_depth =</span> <span class="dv">3</span>)</span>
<span id="cb47-2"><a href="tree-based-methods.html#cb47-2"></a>tflow &lt;-</span>
<span id="cb47-3"><a href="tree-based-methods.html#cb47-3"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb47-4"><a href="tree-based-methods.html#cb47-4"></a><span class="st">  </span><span class="kw">replace_model</span>(dectree)</span>
<span id="cb47-5"><a href="tree-based-methods.html#cb47-5"></a></span>
<span id="cb47-6"><a href="tree-based-methods.html#cb47-6"></a>fit_complex &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb47-7"><a href="tree-based-methods.html#cb47-7"></a>tree &lt;-<span class="st"> </span><span class="kw">pull_tflow_fit</span>(fit_complex)<span class="op">$</span>fit</span>
<span id="cb47-8"><a href="tree-based-methods.html#cb47-8"></a><span class="kw">rpart.plot</span>(tree)</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The tree was reduced considerably now in combination with the minimun number of respondents within each node. In fact, there is only one node that has a sample size lower than <span class="math inline">\(3\%\)</span>. The <code>min_n</code> and <code>tree_depth</code> can help you reduce the overfitting of your tree, but don’t think these are easy fixes. Decision trees are simply to easy to overfit the data and as we’ll see, there are more advanced tree methods that can help to fix this.</p>
<p>Note that we’ve been interpreting decision trees in a ‘subjective’ fashion. That is, we’ve been cutting the nodes of the trees from subjective criteria that makes sense to our research problem. This is how we social scientists would analyze the data. The tree should model our theoretical problem and make substantive sense. However, for machine learning, we have other criteria: how well it predicts. Let’s check how our model predicts at this point:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tree-based-methods.html#cb48-1"></a>fit_complex <span class="op">%&gt;%</span></span>
<span id="cb48-2"><a href="tree-based-methods.html#cb48-2"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb48-3"><a href="tree-based-methods.html#cb48-3"></a><span class="st">  </span><span class="kw">rmse</span>(ST102Q01TA, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       0.514</code></pre>
<p>Our predictions for each set goals is off by around <span class="math inline">\(.5\)</span> in a scale of <span class="math inline">\(1\)</span> through <span class="math inline">\(4\)</span>. This is not terribly bad. For example, it means that for every child that answered a <span class="math inline">\(2\)</span>, on average, we have an error of around <span class="math inline">\(.5\)</span>. This means that any prediction for a single number runs the risk of being wrongly predicting either the number from above or below (a child with a <span class="math inline">\(2\)</span> might get a wrong prediction of <span class="math inline">\(3\)</span> or a <span class="math inline">\(1\)</span> but hardly a <span class="math inline">\(4\)</span>). To improve prediction, we can allow <code>tidyflow</code> to search for the best combination of <code>min_n</code> and <code>tree_depth</code> that maximizes prediction. Let’s perform a grid search for these two tuning values. However, let’s set the range of tuning values ourselves:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="tree-based-methods.html#cb50-1"></a>tune_mod &lt;-<span class="st"> </span><span class="kw">update</span>(dectree, <span class="dt">min_n =</span> <span class="kw">tune</span>(), <span class="dt">tree_depth =</span> <span class="kw">tune</span>())</span>
<span id="cb50-2"><a href="tree-based-methods.html#cb50-2"></a></span>
<span id="cb50-3"><a href="tree-based-methods.html#cb50-3"></a>tflow &lt;-</span>
<span id="cb50-4"><a href="tree-based-methods.html#cb50-4"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb50-5"><a href="tree-based-methods.html#cb50-5"></a><span class="st">  </span><span class="kw">plug_resample</span>(vfold_cv, <span class="dt">v =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span></span>
<span id="cb50-6"><a href="tree-based-methods.html#cb50-6"></a><span class="st">  </span><span class="kw">plug_grid</span>(</span>
<span id="cb50-7"><a href="tree-based-methods.html#cb50-7"></a>    expand.grid,</span>
<span id="cb50-8"><a href="tree-based-methods.html#cb50-8"></a>    <span class="dt">tree_depth =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>),</span>
<span id="cb50-9"><a href="tree-based-methods.html#cb50-9"></a>    <span class="dt">min_n =</span> <span class="kw">c</span>(<span class="dv">50</span>, <span class="dv">100</span>)</span>
<span id="cb50-10"><a href="tree-based-methods.html#cb50-10"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb50-11"><a href="tree-based-methods.html#cb50-11"></a><span class="st">  </span><span class="kw">replace_model</span>(tune_mod)</span>
<span id="cb50-12"><a href="tree-based-methods.html#cb50-12"></a></span>
<span id="cb50-13"><a href="tree-based-methods.html#cb50-13"></a>fit_tuned &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb50-14"><a href="tree-based-methods.html#cb50-14"></a></span>
<span id="cb50-15"><a href="tree-based-methods.html#cb50-15"></a>fit_tuned <span class="op">%&gt;%</span></span>
<span id="cb50-16"><a href="tree-based-methods.html#cb50-16"></a><span class="st">  </span><span class="kw">pull_tflow_fit_tuning</span>() <span class="op">%&gt;%</span></span>
<span id="cb50-17"><a href="tree-based-methods.html#cb50-17"></a><span class="st">  </span><span class="kw">show_best</span>(<span class="dt">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 7
##   tree_depth min_n .metric .estimator  mean     n std_err
##        &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
## 1          9    50 rmse    standard   0.459     5  0.0126
## 2          9   100 rmse    standard   0.459     5  0.0126
## 3          3    50 rmse    standard   0.518     5  0.0116
## 4          3   100 rmse    standard   0.518     5  0.0116
## 5          1    50 rmse    standard   0.649     5  0.0102</code></pre>
<p>It seems that our predictions on the training data were slightly overfitting the data, as the best error from the cross-validation search is centered around <code>0.459</code> with a standard error of <code>0.01</code>. Let’s explore whether the error changes between the minimum sample size and the tree depth:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="tree-based-methods.html#cb52-1"></a>tree_depth_lvl &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;Tree depth: &quot;</span>, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>))</span>
<span id="cb52-2"><a href="tree-based-methods.html#cb52-2"></a></span>
<span id="cb52-3"><a href="tree-based-methods.html#cb52-3"></a>fit_tuned <span class="op">%&gt;%</span></span>
<span id="cb52-4"><a href="tree-based-methods.html#cb52-4"></a><span class="st">  </span><span class="kw">pull_tflow_fit_tuning</span>() <span class="op">%&gt;%</span></span>
<span id="cb52-5"><a href="tree-based-methods.html#cb52-5"></a><span class="st">  </span><span class="kw">collect_metrics</span>() <span class="op">%&gt;%</span></span>
<span id="cb52-6"><a href="tree-based-methods.html#cb52-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ci_low =</span> mean <span class="op">-</span><span class="st"> </span>(<span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std_err),</span>
<span id="cb52-7"><a href="tree-based-methods.html#cb52-7"></a>         <span class="dt">ci_high =</span> mean <span class="op">+</span><span class="st"> </span>(<span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std_err),</span>
<span id="cb52-8"><a href="tree-based-methods.html#cb52-8"></a>         <span class="dt">tree_depth =</span> <span class="kw">factor</span>(<span class="kw">paste0</span>(<span class="st">&quot;Tree depth: &quot;</span>, tree_depth), <span class="dt">levels =</span> tree_depth_lvl),</span>
<span id="cb52-9"><a href="tree-based-methods.html#cb52-9"></a>         <span class="dt">min_n =</span> <span class="kw">factor</span>(min_n, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;50&quot;</span>, <span class="st">&quot;100&quot;</span>))) <span class="op">%&gt;%</span></span>
<span id="cb52-10"><a href="tree-based-methods.html#cb52-10"></a><span class="st">  </span><span class="kw">filter</span>(.metric <span class="op">==</span><span class="st"> &quot;rmse&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb52-11"><a href="tree-based-methods.html#cb52-11"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(min_n, mean)) <span class="op">+</span></span>
<span id="cb52-12"><a href="tree-based-methods.html#cb52-12"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb52-13"><a href="tree-based-methods.html#cb52-13"></a><span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> ci_low, <span class="dt">ymax =</span> ci_high), <span class="dt">width =</span> <span class="fl">.1</span>) <span class="op">+</span></span>
<span id="cb52-14"><a href="tree-based-methods.html#cb52-14"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="st">&quot;Minimum sample size per node&quot;</span>) <span class="op">+</span></span>
<span id="cb52-15"><a href="tree-based-methods.html#cb52-15"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="st">&quot;Average RMSE&quot;</span>) <span class="op">+</span></span>
<span id="cb52-16"><a href="tree-based-methods.html#cb52-16"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>tree_depth, <span class="dt">nrow =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb52-17"><a href="tree-based-methods.html#cb52-17"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>On the <code>x</code> axis we have the minimum sample size per node (these are the values for <code>min_n</code>) and on the <code>y</code> axis we have the error of the model through cross-validation (the <span class="math inline">\(RMSE\)</span>). The lower each points is on the plot, the better, since it means that the error is lower.</p>
<p>Let’s begin with the first plot on the left. The points represent the error of the model with different sample sizes for the nodes with a fixed tree depth of <span class="math inline">\(1\)</span>. For a tree depth of <span class="math inline">\(1\)</span>, the error of the model is around <code>.65</code>. However, as the number of trees increases (the additional <em>plots</em> to the right), the error comes down to nearly <code>.47</code> when there is a <code>tree_depth</code> of 9. It seems that the simplest model with the lowest <span class="math inline">\(RMSE\)</span> has a <code>tree_depth</code> of 9 and a minimum sample size of 50. We calculated this ourselves for this example, but <code>complete_tflow</code> can calculate this for you:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tree-based-methods.html#cb53-1"></a>final_model &lt;-</span>
<span id="cb53-2"><a href="tree-based-methods.html#cb53-2"></a><span class="st">  </span>fit_tuned <span class="op">%&gt;%</span></span>
<span id="cb53-3"><a href="tree-based-methods.html#cb53-3"></a><span class="st">  </span><span class="kw">complete_tflow</span>(<span class="dt">metric =</span> <span class="st">&quot;rmse&quot;</span>,</span>
<span id="cb53-4"><a href="tree-based-methods.html#cb53-4"></a>                 tree_depth,</span>
<span id="cb53-5"><a href="tree-based-methods.html#cb53-5"></a>                 <span class="dt">method =</span> <span class="st">&quot;select_by_one_std_err&quot;</span>)</span>
<span id="cb53-6"><a href="tree-based-methods.html#cb53-6"></a></span>
<span id="cb53-7"><a href="tree-based-methods.html#cb53-7"></a>train_err &lt;-</span>
<span id="cb53-8"><a href="tree-based-methods.html#cb53-8"></a><span class="st">  </span>final_model <span class="op">%&gt;%</span></span>
<span id="cb53-9"><a href="tree-based-methods.html#cb53-9"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb53-10"><a href="tree-based-methods.html#cb53-10"></a><span class="st">  </span><span class="kw">rmse</span>(ST102Q01TA, .pred)</span>
<span id="cb53-11"><a href="tree-based-methods.html#cb53-11"></a></span>
<span id="cb53-12"><a href="tree-based-methods.html#cb53-12"></a>test_err &lt;-</span>
<span id="cb53-13"><a href="tree-based-methods.html#cb53-13"></a><span class="st">  </span>final_model <span class="op">%&gt;%</span></span>
<span id="cb53-14"><a href="tree-based-methods.html#cb53-14"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb53-15"><a href="tree-based-methods.html#cb53-15"></a><span class="st">  </span><span class="kw">rmse</span>(ST102Q01TA, .pred)</span>
<span id="cb53-16"><a href="tree-based-methods.html#cb53-16"></a></span>
<span id="cb53-17"><a href="tree-based-methods.html#cb53-17"></a><span class="kw">c</span>(<span class="st">&quot;testing error&quot;</span> =<span class="st"> </span>test_err<span class="op">$</span>.estimate, <span class="st">&quot;training error&quot;</span> =<span class="st"> </span>train_err<span class="op">$</span>.estimate)</span></code></pre></div>
<pre><code>##  testing error training error 
##      0.4644939      0.4512248</code></pre>
<p>Our testing error and our training error have a difference of only <span class="math inline">\(0.01\)</span>, not bad. The cross-validation tuning seemed to have helped avoid a great deal of overfitting.</p>
<p>Before we go through the next section, I want to briefly mention an alternative to <code>tree_depth</code> and <code>min_n</code>. A technique called ‘tree pruning’ is also very common for modeling decision trees. It first grows a very large and complex tree and <strong>then</strong> starts pruning the leafs. This technique is also very useful but due to the lack of time, we won’t cover this in the course. You can check out the material on this technique from the resources outlined in the first paragraph of this section.</p>
<div id="advancedsplit" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Advanced: how do trees choose where to split?</h3>
<p>Throughout most of the chapter we’ve seen that trees find optimal ‘splits’ that make the respondents very different between the splits and very similar within them. But how do decision trees make these splits? Let’s work out a simple example using the <code>HISEI</code> variable from the first model in this section.</p>
<p><code>HISEI</code> is an index for the socio-economic status of families. It’s continuous and has a distribution like this:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>As we saw in the first tree of this section, <code>HISEI</code> is the <strong>root node</strong>. To decide on the <strong>root node</strong>, the decision tree algorithm chooses a random location in the distribution of <code>HISEI</code> and draws a split:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>The two sides have an average <code>math_score</code> which serves as the baseline for how different these two groups are. At this point, the algorithm does something very simple: for each split, it calculates the <strong>R</strong>esidual <strong>S</strong>um of <strong>S</strong>quares (RSS). This is just the sum of the <code>math_score</code> of each respondent (<span class="math inline">\(math_i\)</span>) minus the average <code>math_score</code> (<span class="math inline">\(\hat{math}\)</span>) for that split squared. In other words, it applies the <span class="math inline">\(RSS\)</span> for each split:</p>
<p><span class="math display">\[\begin{equation}
RSS = \sum_{k = 1}^n(math_i - \hat{math})^2
\end{equation}\]</span></p>
<p>Each side of the split then has a corresponding <span class="math inline">\(RSS\)</span>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>After that, it calculates the total <span class="math inline">\(RSS\)</span> of the split by adding the two <span class="math inline">\(RSS\)</span>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>So far we should have a single random split with an associated <span class="math inline">\(RSS\)</span> for <span class="math inline">\(HISEI\)</span>. The decision tree algorithm is called <em>recursive binary splitting</em> because it is recursive: it repeats itself again many times. It repeats the strategy of <span class="math inline">\(Split\)</span> -&gt; <span class="math inline">\(RSS_{split}\)</span> -&gt; <span class="math inline">\(RSS_{total}\)</span> many times such that we get a distribution of splits and <span class="math inline">\(RSS\)</span> for <span class="math inline">\(HISEI\)</span>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>This produces a distribution of random splits with an associated metric of fit (<span class="math inline">\(RSS\)</span>) for <span class="math inline">\(HISEI\)</span>. <em>Recursive binary splitting</em> applies this same logic to every single variable in the model such that you have a distribution of splits for every single variable:</p>
<pre><code>## # A tibble: 8 x 3
##   variable random_split total_rss            
##   &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt;                
## 1 &quot;HISEI&quot;  41.22        &quot;Total RSS: 34423362&quot;
## 2 &quot;HISEI&quot;  53.77        &quot;Total RSS: 34400218&quot;
## 3 &quot;HISEI&quot;  56.57        &quot;Total RSS: 32523560&quot;
## 4 &quot;&quot;       ...          &quot;&quot;                   
## 5 &quot;FISCED&quot; 2            &quot;Total RSS: 35901660&quot;
## 6 &quot;FISCED&quot; 1            &quot;Total RSS: 36085201&quot;
## 7 &quot;FISCED&quot; 5            &quot;Total RSS: 34083264&quot;
## 8 &quot;&quot;       ...          &quot;&quot;</code></pre>
<p>With such a distribution, the algorithm can objectively ask: which random split best separates the data into two branches with the lowest <span class="math inline">\(RSS\)</span>? And based on that answer, the first <strong>node</strong> is chosen. After this first node is chosen, two branches grow to both sides. The algorithm then applies exactly the same set of rules <em>recursively</em> for each branch until a maximum depth is reached.</p>
<p>Although this explanation will be in nearly all cases invisible to you, this intuition can help you understand better which criteria is used for choosing a split. For example, understanding how this splitting is done gives you insight into how outliers do not affect the selection of splits because the splitting criteria is random and navigates the entire distribution.</p>
<p>In addition, there might be cases where you might want to switch the <span class="math inline">\(RSS\)</span> for another loss function because it makes sense for your problem. For example, using decision trees with binary dependent variables merits another type of loss function: <em>Gini impurity</em>. We won’t delve into this but it serves as an example that these are things which are not fixed. These are decision that depend on your research problem and it might make sense to experiment with them if needed.</p>
</div>
</div>
<div id="bagging" class="section level2">
<h2><span class="header-section-number">3.2</span> Bagging</h2>
<p>The problem with decision trees is that even if you work really hard to avoid overfitting, they can be very susceptible to the exact composition of the data. For some extreme cases, you might even get completely different trees every time you run your model. Quite literally, running the same model might offer very different trees if some part of the sample changes. This small simulation predicts <code>math_score</code> on all variables in the <code>pisa</code> data set but in each iteration, makes a random sample from the total dataset:</p>
<div class="figure"><span id="fig:manydtrees"></span>
<img src="03_trees_files/figure-html/manydtrees-1.png" alt="Visualization of many trees from the sample with varying compositions" width="99%" />
<p class="caption">
Figure 3.1: Visualization of many trees from the sample with varying compositions
</p>
</div>
<p>These drastic differences between each iteration is because decision trees have a lot of variance and very little bias. They learn the current data very well (little bias) but if you generalize them to new data, they can perform very badly (a lot of variance). This is where bagging, or <strong>B</strong>ootstrap <strong>Agg</strong>regation comes in.</p>
<p>Before we explain what bagging is all about, let’s spend a minute explaining what bootstrapping is. Let’s work out a manual example and limit our <code>pisa</code> dataset to only five rows, keep a few selected columns and add a unique id for each row:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tree-based-methods.html#cb56-1"></a>sel_cols &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;math_score&quot;</span>, <span class="st">&quot;HISEI&quot;</span>, <span class="st">&quot;REPEAT&quot;</span>, <span class="st">&quot;IMMIG&quot;</span>, <span class="st">&quot;read_score&quot;</span>)</span>
<span id="cb56-2"><a href="tree-based-methods.html#cb56-2"></a>pisa_small &lt;-<span class="st"> </span>pisa[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, sel_cols]</span>
<span id="cb56-3"><a href="tree-based-methods.html#cb56-3"></a>pisa_small<span class="op">$</span>id &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span></span>
<span id="cb56-4"><a href="tree-based-methods.html#cb56-4"></a>pisa_small</span></code></pre></div>
<pre><code>##   math_score HISEI REPEAT IMMIG read_score id
## 1   512.7125 28.60      0     1   544.2085  1
## 2   427.3615 59.89      0     1   432.2518  2
## 3   449.9545 39.02      0     1   503.9496  3
## 4   474.5553 26.60      0     1   437.7777  4
## 5   469.1545 76.65      0     1   535.9487  5</code></pre>
<p>This is the same <code>pisa</code> dataset but only with the first five rows, and id column for each respondent and some columns. Bootstraping is a statistical technique that randomly picks observations from the sample. This means that some observations might get picked while others might no. In fact, some observations might even get picked many times! We can do this manually in R:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tree-based-methods.html#cb58-1"></a><span class="co"># Sample from the number of rows in `pisa_small`</span></span>
<span id="cb58-2"><a href="tree-based-methods.html#cb58-2"></a><span class="co"># and allow certain numbers to be replaced.</span></span>
<span id="cb58-3"><a href="tree-based-methods.html#cb58-3"></a><span class="kw">set.seed</span>(<span class="dv">23551</span>)</span>
<span id="cb58-4"><a href="tree-based-methods.html#cb58-4"></a>row_index &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(pisa_small), <span class="dt">replace =</span> <span class="ot">TRUE</span>)</span>
<span id="cb58-5"><a href="tree-based-methods.html#cb58-5"></a>pisa_small[row_index, ]</span></code></pre></div>
<pre><code>##     math_score HISEI REPEAT IMMIG read_score id
## 1     512.7125 28.60      0     1   544.2085  1
## 4     474.5553 26.60      0     1   437.7777  4
## 4.1   474.5553 26.60      0     1   437.7777  4
## 3     449.9545 39.02      0     1   503.9496  3
## 5     469.1545 76.65      0     1   535.9487  5</code></pre>
<p>We randomly sampled from the data and got the respondent number four repeated twice. We can run this many times and get many <strong>resamples</strong> of our data:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tree-based-methods.html#cb60-1"></a><span class="kw">lapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="cf">function</span>(x) {</span>
<span id="cb60-2"><a href="tree-based-methods.html#cb60-2"></a>  row_index &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(pisa_small), <span class="dt">replace =</span> <span class="ot">TRUE</span>)</span>
<span id="cb60-3"><a href="tree-based-methods.html#cb60-3"></a>  pisa_small[row_index, ]</span>
<span id="cb60-4"><a href="tree-based-methods.html#cb60-4"></a>})</span></code></pre></div>
<pre><code>## [[1]]
##     math_score HISEI REPEAT IMMIG read_score id
## 3     449.9545 39.02      0     1   503.9496  3
## 5     469.1545 76.65      0     1   535.9487  5
## 3.1   449.9545 39.02      0     1   503.9496  3
## 1     512.7125 28.60      0     1   544.2085  1
## 3.2   449.9545 39.02      0     1   503.9496  3
## 
## [[2]]
##     math_score HISEI REPEAT IMMIG read_score id
## 1     512.7125  28.6      0     1   544.2085  1
## 4     474.5553  26.6      0     1   437.7777  4
## 4.1   474.5553  26.6      0     1   437.7777  4
## 4.2   474.5553  26.6      0     1   437.7777  4
## 4.3   474.5553  26.6      0     1   437.7777  4</code></pre>
<p>Since the choosing of rows is random, in some instances we might randomly obtain the same row repeated ten times, in others only one time and others even zero times! This is what bootstrapping is all about. If we run <span class="math inline">\(10\)</span> bootstraps, it just means we have <span class="math inline">\(10\)</span> datasets where in each one some rows are repeated many times and others are randomly removed.</p>
<p>Bootstrapping is mainly used to calculate statistics such as standard errors and standard deviations because it has very nice properties to estimate uncertainty in situations where its impossible to calculate it. However, it also has advantages for reducing the variance in models such as decision trees.</p>
<p>Let’s get back to how bagging works. Bagging works by bootstraping your data <span class="math inline">\(N\)</span> times and fitting <span class="math inline">\(N\)</span> decision trees. Each of these decision trees has a lot of variance because we allow the tree to overfit the data. The trick with bagging is that we <strong>average</strong> over the predictions of all the <span class="math inline">\(N\)</span> decision trees, improving the high variability of each single decision tree.</p>
<p>In the same spirit as before, let’s work out a manual example just so you can truly grasp that intuition. However, don’t worry, there are functions inside <code>tidymodels</code> and <code>tidyflow</code> that will perform all of this for you.</p>
<p>Let’s adapt the code from above to use the original <code>pisa</code> data, sample only 60% of the data in each bootstrap and generate 20 copies of our data with random picks of rows in each iteration:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="tree-based-methods.html#cb62-1"></a>pisa<span class="op">$</span>id &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(pisa)</span>
<span id="cb62-2"><a href="tree-based-methods.html#cb62-2"></a>bootstrap_pisa &lt;-</span>
<span id="cb62-3"><a href="tree-based-methods.html#cb62-3"></a><span class="st">  </span><span class="kw">lapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>, <span class="cf">function</span>(x) {</span>
<span id="cb62-4"><a href="tree-based-methods.html#cb62-4"></a>    row_index &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(pisa) <span class="op">*</span><span class="st"> </span><span class="fl">.6</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</span>
<span id="cb62-5"><a href="tree-based-methods.html#cb62-5"></a>    pisa[row_index, ]</span>
<span id="cb62-6"><a href="tree-based-methods.html#cb62-6"></a>  })</span></code></pre></div>
<p>The result is named <code>bootstrap_pisa</code> and is list with 20 data frames. You can inspect the first two with <code>bootstrap_pisa[[1]]</code> and <code>bootstrap_pisa[[2]]</code>. Inside each of these, there should be a data frame with 60% of the original number of rows of the <code>pisa</code> data where each row was randomly picked. Some of these might be repeated many times, others might just be there once and others might not even be there.</p>
<p>Let’s now loop over these 20 datasets, fit a decision tree to each one and predict on the original <code>pisa</code> data. The result of this loop should be 20 data frames each with a prediction for every respondent:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tree-based-methods.html#cb63-1"></a>tflow &lt;-</span>
<span id="cb63-2"><a href="tree-based-methods.html#cb63-2"></a><span class="st">  </span><span class="kw">tidyflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb63-3"><a href="tree-based-methods.html#cb63-3"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>.) <span class="op">%&gt;%</span></span>
<span id="cb63-4"><a href="tree-based-methods.html#cb63-4"></a><span class="st">  </span><span class="kw">plug_model</span>(<span class="kw">decision_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>))</span>
<span id="cb63-5"><a href="tree-based-methods.html#cb63-5"></a></span>
<span id="cb63-6"><a href="tree-based-methods.html#cb63-6"></a>all_pred_models &lt;-</span>
<span id="cb63-7"><a href="tree-based-methods.html#cb63-7"></a><span class="st">  </span><span class="kw">lapply</span>(bootstrap_pisa, <span class="cf">function</span>(x) {</span>
<span id="cb63-8"><a href="tree-based-methods.html#cb63-8"></a>    small_model &lt;-</span>
<span id="cb63-9"><a href="tree-based-methods.html#cb63-9"></a><span class="st">      </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb63-10"><a href="tree-based-methods.html#cb63-10"></a><span class="st">      </span><span class="kw">plug_data</span>(x) <span class="op">%&gt;%</span></span>
<span id="cb63-11"><a href="tree-based-methods.html#cb63-11"></a><span class="st">      </span><span class="kw">fit</span>()</span>
<span id="cb63-12"><a href="tree-based-methods.html#cb63-12"></a></span>
<span id="cb63-13"><a href="tree-based-methods.html#cb63-13"></a>    <span class="kw">cbind</span>(</span>
<span id="cb63-14"><a href="tree-based-methods.html#cb63-14"></a>      pisa[<span class="st">&quot;id&quot;</span>],</span>
<span id="cb63-15"><a href="tree-based-methods.html#cb63-15"></a>      <span class="kw">predict</span>(small_model, <span class="dt">new_data =</span> pisa)</span>
<span id="cb63-16"><a href="tree-based-methods.html#cb63-16"></a>    )</span>
<span id="cb63-17"><a href="tree-based-methods.html#cb63-17"></a>  })</span></code></pre></div>
<p>The first slot contains predictions for all respondents. Let’s confirm that:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="tree-based-methods.html#cb64-1"></a><span class="kw">head</span>(all_pred_models[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>##   id    .pred
## 1  1 493.6071
## 2  2 378.5172
## 3  3 440.5835
## 4  4 440.5835
## 5  5 493.6071
## 6  6 440.5835</code></pre>
<p>Here we only show the first five rows, but you can check that it matches the same number of rows as the original <code>pisa</code> with <code>nrow(all_pred_model[[1]])</code> and <code>nrow(pisa)</code>. Let’s confirm the same thing for the second slot:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="tree-based-methods.html#cb66-1"></a><span class="kw">head</span>(all_pred_models[[<span class="dv">2</span>]])</span></code></pre></div>
<pre><code>##   id    .pred
## 1  1 486.7747
## 2  2 432.6909
## 3  3 432.6909
## 4  4 432.6909
## 5  5 486.7747
## 6  6 486.7747</code></pre>
<p>The second slot also contains predictions for all respondents but they are different from the first slot because they are based on a random sample. This same logic is repeated 20 times such that every respondent has 20 predictions. The trick behind bagging is that it <strong>averages</strong> the prediction of each respondent over the 20 bootstraps.</p>
<p>This averaging has two advantages. First, it allows each single tree to grow as much as possible, allowing it to have a lot of variance and little bias. This has a good property which is little bias but a negative aspect, which is a lot of variance. Bagging compensates this high level of variance by averaging the predictions of all the small trees:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="tree-based-methods.html#cb68-1"></a><span class="co"># Combine all the 20 predictions into one data frame</span></span>
<span id="cb68-2"><a href="tree-based-methods.html#cb68-2"></a>all_combined &lt;-<span class="st"> </span>all_pred_models[[<span class="dv">1</span>]]</span>
<span id="cb68-3"><a href="tree-based-methods.html#cb68-3"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(all_pred_models)[<span class="op">-</span><span class="dv">1</span>]) {</span>
<span id="cb68-4"><a href="tree-based-methods.html#cb68-4"></a>  all_combined &lt;-<span class="st"> </span><span class="kw">cbind</span>(all_combined, all_pred_models[[i]][<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb68-5"><a href="tree-based-methods.html#cb68-5"></a>}</span>
<span id="cb68-6"><a href="tree-based-methods.html#cb68-6"></a></span>
<span id="cb68-7"><a href="tree-based-methods.html#cb68-7"></a><span class="co"># Average over the 20 predictions</span></span>
<span id="cb68-8"><a href="tree-based-methods.html#cb68-8"></a>res &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">id =</span> all_combined[<span class="dv">1</span>], <span class="dt">final_pred =</span> <span class="kw">rowMeans</span>(all_combined[<span class="op">-</span><span class="dv">1</span>]))</span>
<span id="cb68-9"><a href="tree-based-methods.html#cb68-9"></a></span>
<span id="cb68-10"><a href="tree-based-methods.html#cb68-10"></a><span class="co"># Final prediction for each respondent</span></span>
<span id="cb68-11"><a href="tree-based-methods.html#cb68-11"></a><span class="kw">head</span>(res)</span></code></pre></div>
<pre><code>##   id final_pred
## 1  1   494.1934
## 2  2   403.6330
## 3  3   436.1936
## 4  4   443.5922
## 5  5   491.6506
## 6  6   457.9670</code></pre>
<p>We get a final prediction for each respondent. If we wanted to, we could calculate the standard deviation of these 20 predictions for each respondent and generate uncertainty intervals around each respondent’s predictions. More often than not, this is a good idea.</p>
<p>In the previous example we used 20 bootstraps for the sake of simplicity but generally speaking as the number of trees increases, the less variance we will have in the final prediction and thus a stronger model. We can see more clearly the power of combining many trees with the simulation below:</p>
<p><img src="img/bagging_sim.png" width="80%" style="display: block; margin: auto;" /></p>
<p>The <code>x</code> axis shows the number of bootstraps (or fitted decision trees, it’s the same) and the <code>y</code> axis shows the average <span class="math inline">\(RMSE\)</span> in <code>math_score</code> for each of these bagged trees. As we increase the number of decision trees (or bootstraps, it’s the same), there is a substantial reduction in the error rate of <code>math_score</code>. This is an impressive improvement relative to our initial single decision tree.</p>
<p>Having seen the power of increasing the number of trees, how many trees should your model use? For models which exhibit reasonable levels of variability (like our <code>math_score</code> example), <span class="math inline">\(100\)</span>-<span class="math inline">\(200\)</span> bootstraps is often enough to stabilize the error in the predictions. However, very unstable models might require up to <span class="math inline">\(500\)</span> bootstraps.</p>
<p>Let’s fit the same model we just implemented manually above using <code>tidymodels</code> and <code>tidyflow</code>. Bagged trees can be implemented with the function <code>bag_tree</code> from the package <code>baguette</code>. With this package we can control the number of bootstraps with the argument <code>times</code>. We can define our model as usual using <code>tidyflow</code>:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="tree-based-methods.html#cb70-1"></a>btree &lt;-<span class="st"> </span><span class="kw">bag_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>, <span class="dt">times =</span> <span class="dv">50</span>)</span>
<span id="cb70-2"><a href="tree-based-methods.html#cb70-2"></a></span>
<span id="cb70-3"><a href="tree-based-methods.html#cb70-3"></a>tflow &lt;-</span>
<span id="cb70-4"><a href="tree-based-methods.html#cb70-4"></a><span class="st">  </span>pisa <span class="op">%&gt;%</span></span>
<span id="cb70-5"><a href="tree-based-methods.html#cb70-5"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">566521</span>) <span class="op">%&gt;%</span></span>
<span id="cb70-6"><a href="tree-based-methods.html#cb70-6"></a><span class="st">  </span><span class="kw">plug_split</span>(initial_split) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb70-7"><a href="tree-based-methods.html#cb70-7"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>.) <span class="op">%&gt;%</span></span>
<span id="cb70-8"><a href="tree-based-methods.html#cb70-8"></a><span class="st">  </span><span class="kw">plug_model</span>(btree)</span>
<span id="cb70-9"><a href="tree-based-methods.html#cb70-9"></a></span>
<span id="cb70-10"><a href="tree-based-methods.html#cb70-10"></a>tflow</span></code></pre></div>
<pre><code>## ══ Tidyflow ════════════════════════════════════════════════════════════════════
## Data: 4.84K rows x 502 columns
## Split: initial_split w/ default args
## Formula: math_score ~ .
## Resample: None
## Grid: None
## Model:
## Bagged Decision Tree Model Specification (regression)
## 
## Main Arguments:
##   cost_complexity = 0
##   min_n = 2
## 
## Engine-Specific Arguments:
##   times = 50
## 
## Computational engine: rpart</code></pre>
<p>You might be asking yourself, why don’t we define <code>bootstraps</code> inside <code>plug_resample</code>? After all,<code>bootstraps</code> <strong>is</strong> a resampling technique. We could do that but it doesn’t make sense in this context. <code>plug_resample</code> is aimed more towards doing grid search of tuning values together with <code>plug_grid</code>. Since <code>bag_trees</code> is not performing any type of grid search but rather fitting a model many times and making predictions, it automatically incorporates this procedure inside <code>bag_trees</code>. If instead we were doing a grid search of let’s say, <code>min_n</code> and <code>tree_depth</code> for <code>bag_tree</code>, using <code>plug_resample</code> with <code>boostraps</code> would be perfectly reasonable.</p>
<p>Let’s fit both a simple decision tree and the bagged decision tree, predict on the training set and record the average <span class="math inline">\(RMSE\)</span> for both:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="tree-based-methods.html#cb72-1"></a>res_btree &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb72-2"><a href="tree-based-methods.html#cb72-2"></a>res_dtree &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_model</span>(<span class="kw">decision_tree</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb72-3"><a href="tree-based-methods.html#cb72-3"></a></span>
<span id="cb72-4"><a href="tree-based-methods.html#cb72-4"></a>rmse_dtree &lt;-</span>
<span id="cb72-5"><a href="tree-based-methods.html#cb72-5"></a><span class="st">  </span>res_dtree <span class="op">%&gt;%</span></span>
<span id="cb72-6"><a href="tree-based-methods.html#cb72-6"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb72-7"><a href="tree-based-methods.html#cb72-7"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb72-8"><a href="tree-based-methods.html#cb72-8"></a></span>
<span id="cb72-9"><a href="tree-based-methods.html#cb72-9"></a>rmse_btree &lt;-</span>
<span id="cb72-10"><a href="tree-based-methods.html#cb72-10"></a><span class="st">  </span>res_btree <span class="op">%&gt;%</span></span>
<span id="cb72-11"><a href="tree-based-methods.html#cb72-11"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb72-12"><a href="tree-based-methods.html#cb72-12"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb72-13"><a href="tree-based-methods.html#cb72-13"></a></span>
<span id="cb72-14"><a href="tree-based-methods.html#cb72-14"></a><span class="kw">c</span>(<span class="st">&quot;Decision tree&quot;</span> =<span class="st"> </span>rmse_dtree<span class="op">$</span>.estimate, <span class="st">&quot;Bagged decision tree&quot;</span> =<span class="st"> </span>rmse_btree<span class="op">$</span>.estimate)</span></code></pre></div>
<pre><code>##        Decision tree Bagged decision tree 
##             33.85131             11.33018</code></pre>
<p>The bagged decision tree improves the error rate from <span class="math inline">\(33\)</span> math test points to <span class="math inline">\(11\)</span>. That is a <span class="math inline">\(66\%\)</span> reduction in the error rate! That is an impressive improvement for such a simple extension of decision trees. We might decide to improve upon our model by tweaking <code>min_n</code> and <code>tree_depth</code> but you’ll be doing that in the exercises. Instead, let’s predict on the testing data to check whether how much our final model is overfitting the data.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="tree-based-methods.html#cb74-1"></a>rmse_dtree_test &lt;-</span>
<span id="cb74-2"><a href="tree-based-methods.html#cb74-2"></a><span class="st">  </span>res_dtree <span class="op">%&gt;%</span></span>
<span id="cb74-3"><a href="tree-based-methods.html#cb74-3"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb74-4"><a href="tree-based-methods.html#cb74-4"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb74-5"><a href="tree-based-methods.html#cb74-5"></a></span>
<span id="cb74-6"><a href="tree-based-methods.html#cb74-6"></a>rmse_btree_test &lt;-</span>
<span id="cb74-7"><a href="tree-based-methods.html#cb74-7"></a><span class="st">  </span>res_btree <span class="op">%&gt;%</span></span>
<span id="cb74-8"><a href="tree-based-methods.html#cb74-8"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb74-9"><a href="tree-based-methods.html#cb74-9"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb74-10"><a href="tree-based-methods.html#cb74-10"></a></span>
<span id="cb74-11"><a href="tree-based-methods.html#cb74-11"></a><span class="kw">c</span>(<span class="st">&quot;Decision tree&quot;</span> =<span class="st"> </span>rmse_dtree_test<span class="op">$</span>.estimate, <span class="st">&quot;Bagged decision tree&quot;</span> =<span class="st"> </span>rmse_btree_test<span class="op">$</span>.estimate)</span></code></pre></div>
<pre><code>##        Decision tree Bagged decision tree 
##             34.88733             28.87435</code></pre>
<p>It looks like our model is better than the decision tree but it was overfitting the training data considerably.</p>
<p>As all other models, bagging also has limitations. First, although bagged decision trees offer improved predictions over single decision trees, they do this at the expense of interpretability. Unfortunately, there is no equivalent of an ‘average’ tree that we can visualize. Remember, we have <span class="math inline">\(100\)</span> predictions from <span class="math inline">\(100\)</span> different trees. It is not possible nor advisable to visualize <span class="math inline">\(100\)</span> trees. Instead, we can look at the average variable importance. Bagging offers the ‘contribution’ of each variable using loss functions. For continuous variables, it uses the <span class="math inline">\(RSS\)</span> (which we have described and used throughout this chapter) and for binary variables it uses the Gini index. We can look at the importance of the variables to get a notion of which variables are contributing the most for predictions:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="tree-based-methods.html#cb76-1"></a>res_btree <span class="op">%&gt;%</span></span>
<span id="cb76-2"><a href="tree-based-methods.html#cb76-2"></a><span class="st">  </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span></span>
<span id="cb76-3"><a href="tree-based-methods.html#cb76-3"></a><span class="st">  </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span></span>
<span id="cb76-4"><a href="tree-based-methods.html#cb76-4"></a><span class="st">  </span><span class="kw">var_imp</span>()</span></code></pre></div>
<pre><code>## # A tibble: 501 x 4
##    term           value std.error  used
##    &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
##  1 scie_score 23363949.    75426.    50
##  2 read_score 17033482.    69939.    50
##  3 ST166Q03HA  5913918.    66479.    50
##  4 METASPAM    5671665.    68871.    50
##  5 IC152Q08HA  3850699.   304274.    49
##  6 PISADIFF    3046729.   362250.    50
##  7 IC010Q06NA  2691482.   355147.    50
##  8 ST013Q01TA   433681.   142604.    50
##  9 ESCS         329367.    16981.    50
## 10 HOMEPOS      258437.    11440.    50
## # … with 491 more rows</code></pre>
<p>Secondly, bagging might seem like a deal breaker for <strong>any</strong> type of model (you can apply it to any type of model such as logistic regression, regularized regression, etc..) but it works well only for models which are very unstable. For example, linear regression and logistic regression are models with very little variance. With enough sample size, running a bagged linear regression should return very similar estimates as a single fitted model.</p>
</div>
<div id="random-forests" class="section level2">
<h2><span class="header-section-number">3.3</span> Random Forests</h2>
<p>In section <a href="tree-based-methods.html#advancedsplit">3.1.1</a> we worked out a simple example on how decision trees choose where to split. If you remember correctly, decision trees evaluate several cutoff points for all the variables in the data. This is done recursively such that in each split, this iteration is performed again for all variables inside the split. This strategy is clever but fails spectacularly whenever some variables are very correlated with the outcome of the decision tree.</p>
<p>I did not present the code for the simulation in figure <a href="tree-based-methods.html#fig:manydtrees">3.1</a> but I purposedly excluded the variables <code>scie_score</code> and <code>read_score</code> from the data. That’s why they’re never in any of the trees. Why did I do that? Because they are extremely correlated to <code>math_score</code> and dominate the entire tree. Here’s the same simulation <strong>including</strong> <code>scie_score</code> and <code>read_score</code>:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>Regardless of how much the data composition changes between every decision tree, <code>scie_score</code> and <code>read_score</code> are virtually the only two variables present. This is called <strong>correlated trees</strong>. They are correlated because the predictions between these different trees will be strongly correlated due to the same main variables dominating the trees.</p>
<p>When performing bagged decision trees this can be a problem given that the whole idea behind bagging is to average predictions from very different trees. If we have a variable that is constantly repeated in every single tree, then the predictions will be very similar. Random Forests are an extension of bagged decision trees because they randomly sample <span class="math inline">\(N\)</span> variables in each split. More specifically, instead of considering all variables in the data, for calculating a given split, random forests pick a random sample of <span class="math inline">\(N\)</span> variables to be considered for that split.</p>
<p>This intuition can be much more accesible through a manual example. Let’s refer back to the first plot of this chapter:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>For estimating the split of <code>HISEI &lt; 56</code>, decision trees evaluate many random splits in the distribution of <code>HISEI</code> and record the total <span class="math inline">\(RSS\)</span> of each split such that you get a distribution of splits:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>This is repeated for <strong>every</strong> variable and then the best split out of all the variables is chosen as the split. Random Forests differ from decision trees in that instead of evaluating cutoff splits for every variable, they evaluate cutoff splits only for a <strong>random sample of <span class="math inline">\(N\)</span> variables</strong>. The number of variables <span class="math inline">\(N\)</span> used for each split can be chosen by the user and often it is chosen through a grid search. For this manual example, let’s just assume we’ll use half of all the variables in <code>pisa</code>.</p>
<p>For the <strong>root node</strong> split, we randomly select half of the variables in <code>pisa</code> (<code>pisa</code> has 502 variables), so we randomly choose 251) variables and allow the decision tree to work as usual. It will calculate many random cutoff points for the 251 variables and choose the most optimal cutoff point among the 251 variables. Once the <strong>root node</strong> is determined, two branches are grown to both sides:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Random Forests repeat exactly the same logic for <strong>every</strong> split. For example, to determine the best split for the left branch, it randomly samples 251 variables from the total of 502 but this time limiting the sample to those with <code>HISEI &lt; 56</code>. Similarly for the right branch, it will randomly select 251 variables for those with <code>HISEI &gt; 56</code> and determine the best cutoff split from these limited number of variables. This is then repeated recursively for every split until the usual tree stopping criteria is reached (<code>min_n</code> per node or the <code>tree_depth</code>).</p>
<p>The number of columns to be used in each split is called <code>mtry</code> and there are standard rules of thumb for the number of variables to be randomly picked. In particular, the two most common are <span class="math inline">\(\sqrt{Total\text{ }number\text{ }of\text{ }variables}\)</span> and <span class="math inline">\(\frac{Total\text{ }number\text{ }of\text{ }variables}{3}\)</span>. For example, using the total number of columns from the <code>pisa</code> dataset (502) and the first equation, it would be <span class="math inline">\(\sqrt{502}\)</span> which is equal to 22.4053565, rounded down always to the lowest number which is 22. This means that at every split, the random forest will be picking 22 variables at random. As you might expect, if you set <code>mtry</code> to randomly pick the same number of columns in the data, you’re effectively performing a bagged decision tree rather than a random forest. This would be the equivalent of setting <code>mtry</code> to 502 for the <code>pisa</code> example.</p>
<p>This approach of sampling random columns at each split was created to <strong>uncorrelate</strong> the distribution of decision trees. But, can we be sure that all variables will be used? Well, random sampling is by definition <strong>random</strong>. On average, all variables will be present in some splits and will allow other variables which are not that strongly correlated with the predictor to play a role in the tree construction.</p>
<p>Random Forests have gained a lot of fame because they often achieve incredible accuracy with just standard values for the tuning parameters (for example, the default <code>mtry</code> of <span class="math inline">\(\sqrt{Total\text{ }number\text{ }of\text{ }variables}\)</span> is often enough, without having to try multiple values in a grid search). Let’s try running the same <code>math_score</code> example but with a random forest, predict on the training set and calculate the <span class="math inline">\(RMSE\)</span> of the model:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="tree-based-methods.html#cb78-1"></a><span class="co"># Define the random forest</span></span>
<span id="cb78-2"><a href="tree-based-methods.html#cb78-2"></a>rf_mod &lt;-</span>
<span id="cb78-3"><a href="tree-based-methods.html#cb78-3"></a><span class="st">  </span><span class="kw">rand_forest</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb78-4"><a href="tree-based-methods.html#cb78-4"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>, <span class="dt">importance =</span> <span class="st">&quot;impurity&quot;</span>)</span>
<span id="cb78-5"><a href="tree-based-methods.html#cb78-5"></a></span>
<span id="cb78-6"><a href="tree-based-methods.html#cb78-6"></a><span class="co"># Define the `tidyflow` with the random forest model</span></span>
<span id="cb78-7"><a href="tree-based-methods.html#cb78-7"></a><span class="co"># and include all variables (including scie_score and read_score)</span></span>
<span id="cb78-8"><a href="tree-based-methods.html#cb78-8"></a>tflow &lt;-</span>
<span id="cb78-9"><a href="tree-based-methods.html#cb78-9"></a><span class="st">  </span>pisa <span class="op">%&gt;%</span></span>
<span id="cb78-10"><a href="tree-based-methods.html#cb78-10"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">23151</span>) <span class="op">%&gt;%</span></span>
<span id="cb78-11"><a href="tree-based-methods.html#cb78-11"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>.) <span class="op">%&gt;%</span></span>
<span id="cb78-12"><a href="tree-based-methods.html#cb78-12"></a><span class="st">  </span><span class="kw">plug_split</span>(initial_split) <span class="op">%&gt;%</span></span>
<span id="cb78-13"><a href="tree-based-methods.html#cb78-13"></a><span class="st">  </span><span class="kw">plug_model</span>(rf_mod)</span>
<span id="cb78-14"><a href="tree-based-methods.html#cb78-14"></a></span>
<span id="cb78-15"><a href="tree-based-methods.html#cb78-15"></a>rf_fitted &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb78-16"><a href="tree-based-methods.html#cb78-16"></a></span>
<span id="cb78-17"><a href="tree-based-methods.html#cb78-17"></a>rf_fitted <span class="op">%&gt;%</span></span>
<span id="cb78-18"><a href="tree-based-methods.html#cb78-18"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb78-19"><a href="tree-based-methods.html#cb78-19"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard        16.3</code></pre>
<p>It performs slightly worse than the bagged decision trees (the bagged decision tree had an error of 11.33 math test points). Why is that? Let’s look at which variables are important in the random forest:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="tree-based-methods.html#cb80-1"></a>rf_fitted <span class="op">%&gt;%</span></span>
<span id="cb80-2"><a href="tree-based-methods.html#cb80-2"></a><span class="st">  </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span></span>
<span id="cb80-3"><a href="tree-based-methods.html#cb80-3"></a><span class="st">  </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span></span>
<span id="cb80-4"><a href="tree-based-methods.html#cb80-4"></a><span class="st">  </span><span class="kw">vip</span>() <span class="op">+</span></span>
<span id="cb80-5"><a href="tree-based-methods.html#cb80-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p><code>scie_score</code> and <code>read_score</code> seem to be the most relevant variables. But not only are they the most relevant ones, they are disproportionately the strongest: they both are <strong>seven times</strong> more important than the next most strongest variable.</p>
<p>When there are <strong>only</strong> a few very strong predictors (let’s say, two), then you might have a lot of trees which don’t offer a lot of good predictions. In the model we ran above, the total number of variables used at each split was 22 meaning that if <code>scie_score</code> and <code>read_score</code> are the only important variables that predict <code>math_score</code>, they might be excluded from a lot of the splits. This means that out of the <code>500</code> default trees that are repated, you might get trees which are not better at predicting <code>math_score</code> than random luck.</p>
<p>Based on this intuition, if we increase the number of variables used at each split, we should see an increase in predictive error. Why? Because it means the <code>scie_score</code> and <code>read_score</code> will have greater probability of being included at each split. Let’s try something close to <span class="math inline">\(1/3\)</span> of the number of variables (this is <code>150</code> variables):</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="tree-based-methods.html#cb81-1"></a>rf_mod &lt;-</span>
<span id="cb81-2"><a href="tree-based-methods.html#cb81-2"></a><span class="st">  </span><span class="kw">rand_forest</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">mtry =</span> <span class="dv">150</span>) <span class="op">%&gt;%</span></span>
<span id="cb81-3"><a href="tree-based-methods.html#cb81-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>)</span>
<span id="cb81-4"><a href="tree-based-methods.html#cb81-4"></a></span>
<span id="cb81-5"><a href="tree-based-methods.html#cb81-5"></a>rf_fitted &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_model</span>(rf_mod) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb81-6"><a href="tree-based-methods.html#cb81-6"></a></span>
<span id="cb81-7"><a href="tree-based-methods.html#cb81-7"></a>rf_fitted <span class="op">%&gt;%</span></span>
<span id="cb81-8"><a href="tree-based-methods.html#cb81-8"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb81-9"><a href="tree-based-methods.html#cb81-9"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
<p>The predictive error is reduced to be the same as the one from the bagged decision tree. However, time wise this model is superior than <code>bag_tree</code> because each decision tree uses less variables in total.</p>
<p>You might be asking youself: if bagged decision trees have a lot of correlated trees and the random forest decorrelates the trees, why is it performing just as well and not better? It’s not entirely clear. Random Forests are considered to be a bit of a ‘black box’ and they might work well in certain cases and bad in others. However, having the intuition of how random forests work can help us to approximate a likely explanation.</p>
<p>If <code>scie_score</code> and <code>read_score</code> are the most important variables for predicting <code>math_score</code> and no other variables have strong correlations with <code>math_score</code>, then <strong>excluding</strong> these two variables from a model, might produce trees which just don’t predict <code>math_score</code> well. The value of a random forest over bagged decision trees is that each individual tree must have some sort of <strong>predictive power</strong> despite excluding the strongest predictors.</p>
<p>We can check whether our intuition is correct by running a bagged decision tree and a random forest without <code>scie_score</code> and <code>read_score</code>. If we exclude <code>scie_score</code> and <code>read_score</code>, the remaining variables are very weakly correlated with <code>math_score</code> and thus the random forest produces trees which have richer variability then the bagged trees in predictive performance:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="tree-based-methods.html#cb82-1"></a>rf_mod &lt;-</span>
<span id="cb82-2"><a href="tree-based-methods.html#cb82-2"></a><span class="st">  </span><span class="kw">rand_forest</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">mtry =</span> <span class="dv">150</span>) <span class="op">%&gt;%</span></span>
<span id="cb82-3"><a href="tree-based-methods.html#cb82-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>, <span class="dt">importance =</span> <span class="st">&quot;impurity&quot;</span>)</span>
<span id="cb82-4"><a href="tree-based-methods.html#cb82-4"></a></span>
<span id="cb82-5"><a href="tree-based-methods.html#cb82-5"></a>bt_mod &lt;-</span>
<span id="cb82-6"><a href="tree-based-methods.html#cb82-6"></a><span class="st">  </span><span class="kw">bag_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb82-7"><a href="tree-based-methods.html#cb82-7"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>)</span>
<span id="cb82-8"><a href="tree-based-methods.html#cb82-8"></a></span>
<span id="cb82-9"><a href="tree-based-methods.html#cb82-9"></a>tflow &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_formula</span>(math_score <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>scie_score <span class="op">-</span><span class="st"> </span>read_score)</span>
<span id="cb82-10"><a href="tree-based-methods.html#cb82-10"></a>rf_res &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_model</span>(rf_mod) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb82-11"><a href="tree-based-methods.html#cb82-11"></a>bt_res &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">replace_model</span>(bt_mod) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb82-12"><a href="tree-based-methods.html#cb82-12"></a></span>
<span id="cb82-13"><a href="tree-based-methods.html#cb82-13"></a>bt_rmse &lt;-</span>
<span id="cb82-14"><a href="tree-based-methods.html#cb82-14"></a><span class="st">  </span>bt_res <span class="op">%&gt;%</span></span>
<span id="cb82-15"><a href="tree-based-methods.html#cb82-15"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb82-16"><a href="tree-based-methods.html#cb82-16"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred) <span class="op">%&gt;%</span></span>
<span id="cb82-17"><a href="tree-based-methods.html#cb82-17"></a><span class="st">  </span><span class="kw">pull</span>(.estimate)</span>
<span id="cb82-18"><a href="tree-based-methods.html#cb82-18"></a></span>
<span id="cb82-19"><a href="tree-based-methods.html#cb82-19"></a>rf_rmse &lt;-</span>
<span id="cb82-20"><a href="tree-based-methods.html#cb82-20"></a><span class="st">  </span>rf_res <span class="op">%&gt;%</span></span>
<span id="cb82-21"><a href="tree-based-methods.html#cb82-21"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb82-22"><a href="tree-based-methods.html#cb82-22"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred) <span class="op">%&gt;%</span></span>
<span id="cb82-23"><a href="tree-based-methods.html#cb82-23"></a><span class="st">  </span><span class="kw">pull</span>(.estimate)</span>
<span id="cb82-24"><a href="tree-based-methods.html#cb82-24"></a></span>
<span id="cb82-25"><a href="tree-based-methods.html#cb82-25"></a><span class="kw">c</span>(<span class="st">&quot;Bagged decision trees&quot;</span> =<span class="st"> </span>bt_rmse, <span class="st">&quot;Random Forest&quot;</span> =<span class="st"> </span>rf_rmse)</span></code></pre></div>
<pre><code>## Bagged decision trees         Random Forest 
##              24.32169              21.05124</code></pre>
<p>The random forest is performing better than the bagged decision tree, as our reasoning predicted. Having shown this, since we exclude the two most important predictors, the overall error is <strong>higher</strong> than the previous models. This is expected and we have fitted the previous model just to understand why the random forest is not doing better than the bagged decision tree.</p>
<p>Let’s predict on the testing data to check whether any of the two is overfitting more than the other:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="tree-based-methods.html#cb84-1"></a>bt_rmse &lt;-</span>
<span id="cb84-2"><a href="tree-based-methods.html#cb84-2"></a><span class="st">  </span>bt_res <span class="op">%&gt;%</span></span>
<span id="cb84-3"><a href="tree-based-methods.html#cb84-3"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb84-4"><a href="tree-based-methods.html#cb84-4"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred) <span class="op">%&gt;%</span></span>
<span id="cb84-5"><a href="tree-based-methods.html#cb84-5"></a><span class="st">  </span><span class="kw">pull</span>(.estimate)</span>
<span id="cb84-6"><a href="tree-based-methods.html#cb84-6"></a></span>
<span id="cb84-7"><a href="tree-based-methods.html#cb84-7"></a>rf_rmse &lt;-</span>
<span id="cb84-8"><a href="tree-based-methods.html#cb84-8"></a><span class="st">  </span>rf_res <span class="op">%&gt;%</span></span>
<span id="cb84-9"><a href="tree-based-methods.html#cb84-9"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb84-10"><a href="tree-based-methods.html#cb84-10"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred) <span class="op">%&gt;%</span></span>
<span id="cb84-11"><a href="tree-based-methods.html#cb84-11"></a><span class="st">  </span><span class="kw">pull</span>(.estimate)</span>
<span id="cb84-12"><a href="tree-based-methods.html#cb84-12"></a></span>
<span id="cb84-13"><a href="tree-based-methods.html#cb84-13"></a><span class="kw">c</span>(<span class="st">&quot;Bagged decision trees&quot;</span> =<span class="st"> </span>bt_rmse, <span class="st">&quot;Random Forest&quot;</span> =<span class="st"> </span>rf_rmse)</span></code></pre></div>
<pre><code>## Bagged decision trees         Random Forest 
##              59.64462              55.13338</code></pre>
<p>Both models seem to have been overfitting the data considerably, but they were both overfitting to the same degree: the difference is of around 4 points in both the training and testing data.</p>
<p>Random Forests have several advantages, among which are that they are considerably faster than bagged decision trees because they use only a fraction of the variables used in bagging. However, as we have just showed, their performance gain is not straight forward when the outcome variable only has a few predictors which are strongly correlated with the outcome and very few which are not. There has to be some type of gradient in the correlations between the predictors and the outcome for the random forest to have a considerable improvement.</p>
<p>Our model also offers a good example of how tuning different values of the parameters can offer improved accuracy. If we would’ve stayed with the default <code>mtry</code> of <span class="math inline">\(\sqrt{Total\text{ }number\text{ }of\text{ }variables}\)</span>, the trees would have consistently included uncorrelated variables in each decision tree, making many of our trees obsolete in predictive accuracy. Instead, whenever we’re running random forests, we should try several values of <code>mtry</code> and empirically check which number of columns produce an improvement in the error rate. One important note which sometimes has aroused discussion in machine learning is whether increasing the number of trees increase the chance of overfitting. Increasing the number of trees in a random forest does not lead to increased overfitting because the random forest averages the predictions of all the different trees. Single trees can overfit the data, and that’s ok, because we take the average of all these hundred trees.</p>
<p>Aside from the argument <code>mtry</code>, random forests also have other parameters which can be tuned for their optimal value in a grid search. <code>min_n</code> and <code>trees</code> are the most important ones to tune. Chapter 11 of <span class="citation">Boehmke and Greenwell (<a href="#ref-boehmke2019" role="doc-biblioref">2019</a>)</span> offers good examples on some of the default values you can explore in a random forest and some general intuitions on which parameters have the biggest impact on computational resources, including the time spent running models. This next example can serve as an introductory template if you want to tune some values for your random forest. Beware, searching for the most optimal value of a 10 x 10 grid through 10 cross-validated sets can take a lot of time (even a few hours). You are effectively running 1000 models:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="tree-based-methods.html#cb86-1"></a>rf_mod &lt;-</span>
<span id="cb86-2"><a href="tree-based-methods.html#cb86-2"></a><span class="st">  </span><span class="kw">rand_forest</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>,</span>
<span id="cb86-3"><a href="tree-based-methods.html#cb86-3"></a>              <span class="dt">mtry =</span> <span class="kw">tune</span>(),</span>
<span id="cb86-4"><a href="tree-based-methods.html#cb86-4"></a>              <span class="dt">trees =</span> <span class="kw">tune</span>(),</span>
<span id="cb86-5"><a href="tree-based-methods.html#cb86-5"></a>              <span class="dt">min_n =</span> <span class="kw">tune</span>()) <span class="op">%&gt;%</span></span>
<span id="cb86-6"><a href="tree-based-methods.html#cb86-6"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>)</span>
<span id="cb86-7"><a href="tree-based-methods.html#cb86-7"></a></span>
<span id="cb86-8"><a href="tree-based-methods.html#cb86-8"></a>tflow &lt;-</span>
<span id="cb86-9"><a href="tree-based-methods.html#cb86-9"></a><span class="st">  </span>pisa <span class="op">%&gt;%</span></span>
<span id="cb86-10"><a href="tree-based-methods.html#cb86-10"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">2151</span>) <span class="op">%&gt;%</span></span>
<span id="cb86-11"><a href="tree-based-methods.html#cb86-11"></a><span class="st">  </span><span class="kw">plug_split</span>(initial_split) <span class="op">%&gt;%</span></span>
<span id="cb86-12"><a href="tree-based-methods.html#cb86-12"></a><span class="st">  </span><span class="kw">plug_resample</span>(vfold_cv) <span class="op">%&gt;%</span></span>
<span id="cb86-13"><a href="tree-based-methods.html#cb86-13"></a><span class="st">  </span><span class="kw">plug_grid</span>(grid_random, <span class="dt">levels =</span> <span class="dv">10</span>) <span class="op">%&gt;%</span></span>
<span id="cb86-14"><a href="tree-based-methods.html#cb86-14"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>.) <span class="op">%&gt;%</span></span>
<span id="cb86-15"><a href="tree-based-methods.html#cb86-15"></a><span class="st">  </span><span class="kw">plug_model</span>(rf_mode)</span>
<span id="cb86-16"><a href="tree-based-methods.html#cb86-16"></a></span>
<span id="cb86-17"><a href="tree-based-methods.html#cb86-17"></a>res &lt;-<span class="st"> </span>rf_mod <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb86-18"><a href="tree-based-methods.html#cb86-18"></a>res</span></code></pre></div>
<p>The problem with random forest is mostly about computing time. Although they often do really well with the default values, a user often has to perform a grid search that takes up a lot of time. This can be very time consuming and thus it’s always recommended to start with simple models and then elaborate from there.</p>
</div>
<div id="boosting" class="section level2">
<h2><span class="header-section-number">3.4</span> Boosting</h2>
<p>So far, the tree based methods we’ve seen use decision trees as baseline models and an ensemble approach to calculate the average predictions of all decision trees. Boosting also uses decision trees as the baseline model but the ensemble strategy is fundamentally different.</p>
<p>The name boosting comes from the notion that we fit a weak decision tree and we ‘boost’ it iteratively. This strategy is fundamentally different from bagging and random forests because instead of relying on hundreds of <strong>independent</strong> decision trees, boosting works by recursively boosting the the result of the same decision tree. How does it do that? Let’s work it out manually with our <code>math_score</code> example.</p>
<p>Let’s fit a very weak decision tree of <code>math_score</code> regressed on <code>scie_score</code>.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="tree-based-methods.html#cb87-1"></a>dt_tree &lt;-</span>
<span id="cb87-2"><a href="tree-based-methods.html#cb87-2"></a><span class="st">  </span><span class="kw">decision_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">tree_depth =</span> <span class="dv">1</span>, <span class="dt">min_n =</span> <span class="dv">10</span>) <span class="op">%&gt;%</span></span>
<span id="cb87-3"><a href="tree-based-methods.html#cb87-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>)</span>
<span id="cb87-4"><a href="tree-based-methods.html#cb87-4"></a></span>
<span id="cb87-5"><a href="tree-based-methods.html#cb87-5"></a>pisa_tr &lt;-<span class="st"> </span><span class="kw">training</span>(<span class="kw">initial_split</span>(pisa))</span>
<span id="cb87-6"><a href="tree-based-methods.html#cb87-6"></a></span>
<span id="cb87-7"><a href="tree-based-methods.html#cb87-7"></a>tflow &lt;-</span>
<span id="cb87-8"><a href="tree-based-methods.html#cb87-8"></a><span class="st">  </span>pisa_tr <span class="op">%&gt;%</span></span>
<span id="cb87-9"><a href="tree-based-methods.html#cb87-9"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">51231</span>) <span class="op">%&gt;%</span></span>
<span id="cb87-10"><a href="tree-based-methods.html#cb87-10"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>scie_score) <span class="op">%&gt;%</span></span>
<span id="cb87-11"><a href="tree-based-methods.html#cb87-11"></a><span class="st">  </span><span class="kw">plug_model</span>(dt_tree)</span>
<span id="cb87-12"><a href="tree-based-methods.html#cb87-12"></a></span>
<span id="cb87-13"><a href="tree-based-methods.html#cb87-13"></a>mod1 &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb87-14"><a href="tree-based-methods.html#cb87-14"></a>mod1 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span><span class="st"> </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rpart.plot</span>()</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>This decision tree is very weak. It is only allowed to have a tree depth of 1 which probably means that it is underfitting the data. We can checkout the <span class="math inline">\(RMSE\)</span> of the model:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="tree-based-methods.html#cb88-1"></a>res_mod1 &lt;-</span>
<span id="cb88-2"><a href="tree-based-methods.html#cb88-2"></a><span class="st">  </span>pisa_tr <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb88-3"><a href="tree-based-methods.html#cb88-3"></a><span class="st">  </span><span class="kw">cbind</span>(., <span class="kw">predict</span>(mod1, <span class="dt">new_data =</span> .))</span>
<span id="cb88-4"><a href="tree-based-methods.html#cb88-4"></a></span>
<span id="cb88-5"><a href="tree-based-methods.html#cb88-5"></a>res_mod1 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb88-6"><a href="tree-based-methods.html#cb88-6"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard        55.3</code></pre>
<p>This is not a good model. The <span class="math inline">\(RMSE\)</span> is much bigger than our previous models. In fact, if we look at the residuals, we should see a very strong pattern, something that signals that a model is not properly specified:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="tree-based-methods.html#cb90-1"></a>res_mod1 &lt;-</span>
<span id="cb90-2"><a href="tree-based-methods.html#cb90-2"></a><span class="st">  </span>res_mod1 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb90-3"><a href="tree-based-methods.html#cb90-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">.resid =</span> math_score <span class="op">-</span><span class="st"> </span>.pred)</span>
<span id="cb90-4"><a href="tree-based-methods.html#cb90-4"></a></span>
<span id="cb90-5"><a href="tree-based-methods.html#cb90-5"></a>res_mod1 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb90-6"><a href="tree-based-methods.html#cb90-6"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(scie_score, .resid)) <span class="op">+</span></span>
<span id="cb90-7"><a href="tree-based-methods.html#cb90-7"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">+</span></span>
<span id="cb90-8"><a href="tree-based-methods.html#cb90-8"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Science scores&quot;</span>) <span class="op">+</span></span>
<span id="cb90-9"><a href="tree-based-methods.html#cb90-9"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span><span class="st">  </span></span>
<span id="cb90-10"><a href="tree-based-methods.html#cb90-10"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>Boosting works by predicting the residuals of previous decision tree. In our example, we just fitted our first model and calculated the residuals. Boosting works by fitting a second model but the dependent variable should now be the residuals of the first model rather than the <code>math_score</code> variable. Let’s do that:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="tree-based-methods.html#cb91-1"></a><span class="co"># Convert `math_score` to be the residuals of model 1</span></span>
<span id="cb91-2"><a href="tree-based-methods.html#cb91-2"></a>res_mod1 &lt;-<span class="st"> </span><span class="kw">mutate</span>(res_mod1, <span class="dt">math_score =</span> .resid)</span>
<span id="cb91-3"><a href="tree-based-methods.html#cb91-3"></a></span>
<span id="cb91-4"><a href="tree-based-methods.html#cb91-4"></a><span class="co"># Replace the new data in our `tflow`</span></span>
<span id="cb91-5"><a href="tree-based-methods.html#cb91-5"></a><span class="co"># In the data `res_mod1`, `math_score`</span></span>
<span id="cb91-6"><a href="tree-based-methods.html#cb91-6"></a><span class="co"># is now the residuals of the first model</span></span>
<span id="cb91-7"><a href="tree-based-methods.html#cb91-7"></a>mod2 &lt;-</span>
<span id="cb91-8"><a href="tree-based-methods.html#cb91-8"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb91-9"><a href="tree-based-methods.html#cb91-9"></a><span class="st">  </span><span class="kw">replace_data</span>(res_mod1) <span class="op">%&gt;%</span></span>
<span id="cb91-10"><a href="tree-based-methods.html#cb91-10"></a><span class="st">  </span><span class="kw">fit</span>()</span>
<span id="cb91-11"><a href="tree-based-methods.html#cb91-11"></a></span>
<span id="cb91-12"><a href="tree-based-methods.html#cb91-12"></a>mod2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span><span class="st"> </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rpart.plot</span>()</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>This second model is exactly the same as the first model with the only difference that the dependent variable is the residuals (the unexplained test scores from the first model) of the first model. You can actually see a hint of this in the average score of the dependent variable in the two leaf nodes: they are both in the scale of residuals rather than the scale of <code>math_score</code> (the average <code>math_score</code> is between 300 and 600 points whereas the average of each leaf node is very far from this). Let’s visualize the residuals from the <strong>second</strong> model:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="tree-based-methods.html#cb92-1"></a>res_mod2 &lt;-</span>
<span id="cb92-2"><a href="tree-based-methods.html#cb92-2"></a><span class="st">  </span>pisa_tr <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb92-3"><a href="tree-based-methods.html#cb92-3"></a><span class="st">  </span><span class="kw">cbind</span>(., <span class="kw">predict</span>(mod2, <span class="dt">new_data =</span> .)) <span class="op">%&gt;%</span></span>
<span id="cb92-4"><a href="tree-based-methods.html#cb92-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">.resid =</span> math_score <span class="op">-</span><span class="st"> </span>.pred)</span>
<span id="cb92-5"><a href="tree-based-methods.html#cb92-5"></a></span>
<span id="cb92-6"><a href="tree-based-methods.html#cb92-6"></a>res_mod2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb92-7"><a href="tree-based-methods.html#cb92-7"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(scie_score, .resid)) <span class="op">+</span></span>
<span id="cb92-8"><a href="tree-based-methods.html#cb92-8"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">+</span></span>
<span id="cb92-9"><a href="tree-based-methods.html#cb92-9"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Science scores&quot;</span>) <span class="op">+</span></span>
<span id="cb92-10"><a href="tree-based-methods.html#cb92-10"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span><span class="st">  </span></span>
<span id="cb92-11"><a href="tree-based-methods.html#cb92-11"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="03_trees_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>The pattern seems to have changed although it’s not clear that it’s closer to a random pattern. In the small-scale example we just did, we only fitted two models (or in machine learning jargon, <strong>two trees</strong>). If we fitted 20 trees, each using the previous model’s residuals as the dependent variable, we can start to see how the residuals are converging towards randonmness:</p>
<p><img src="03_trees_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>As each model tries to improve on the previous model’s residuals, the pattern in the residual converges towards randomness. This means that most of the signal in the model has been captured and the remaining residuals are just random noise.</p>
<p>Understanding this iterative process gives a more intuitive explanation to the term boosting. Boosting is a way for each model to boost the last model’s performance by focusing mostly on observations which had big residuals (and thus greater error).</p>
<p>Suppose that you have now fitted 20 trees. This means that each of the respondents in the data will have 20 predictions. However, these predictions are not the same as in bagging and random forest: you cannot take the average of these predictions because they are not in the same metric as <code>math_score</code>. What? What do we mean that they’re not in the same metric? Let’s compare the predictions of our first model and the second model:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="tree-based-methods.html#cb93-1"></a>mod1_pred &lt;-<span class="st"> </span><span class="kw">predict</span>(mod1, <span class="dt">new_data =</span> pisa_tr)</span>
<span id="cb93-2"><a href="tree-based-methods.html#cb93-2"></a><span class="kw">names</span>(mod1_pred) &lt;-<span class="st"> &quot;pred_mod1&quot;</span></span>
<span id="cb93-3"><a href="tree-based-methods.html#cb93-3"></a>mod2_pred &lt;-<span class="st"> </span><span class="kw">predict</span>(mod2, <span class="dt">new_data =</span> pisa_tr)</span>
<span id="cb93-4"><a href="tree-based-methods.html#cb93-4"></a><span class="kw">names</span>(mod2_pred) &lt;-<span class="st"> &quot;pred_mod2&quot;</span></span>
<span id="cb93-5"><a href="tree-based-methods.html#cb93-5"></a></span>
<span id="cb93-6"><a href="tree-based-methods.html#cb93-6"></a>resid_pred &lt;-<span class="st"> </span><span class="kw">cbind</span>(mod1_pred, mod2_pred)</span>
<span id="cb93-7"><a href="tree-based-methods.html#cb93-7"></a><span class="kw">head</span>(resid_pred)</span></code></pre></div>
<pre><code>##   pred_mod1 pred_mod2
## 1  535.6033 -10.47568
## 2  401.1973 -10.47568
## 3  401.1973 -10.47568
## 4  535.6033 -10.47568
## 5  401.1973 -10.47568
## 6  535.6033 -10.47568</code></pre>
<p>The predictions from the first model are in the scale of <code>math_score</code>, mostly between 300 and 600 points. However, the predictions of the second model are very small compared to the first predictions. This is because the dependent variable from the second model is the <strong>residuals</strong> from the first model. All predictions will thus be in the scale of the residuals!</p>
<p>If we ran 20 trees, the predictions from the first model will always be in the scale of the dependent variable while the predictions of the remaining 19 trees will be in the scale of the residuals. With these weird looking 20 predictive values, how can you arrive at the final prediction for each respondent? By adding up the predictions of the 20 trees for each respondent.</p>
<p>For our small-scale example, we can do that with <code>rowSums</code>:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="tree-based-methods.html#cb95-1"></a>resid_pred<span class="op">$</span>final_pred &lt;-<span class="st"> </span><span class="kw">rowSums</span>(resid_pred)</span>
<span id="cb95-2"><a href="tree-based-methods.html#cb95-2"></a><span class="kw">head</span>(resid_pred)</span></code></pre></div>
<pre><code>##   pred_mod1 pred_mod2 final_pred
## 1  535.6033 -10.47568   525.1276
## 2  401.1973 -10.47568   390.7216
## 3  401.1973 -10.47568   390.7216
## 4  535.6033 -10.47568   525.1276
## 5  401.1973 -10.47568   390.7216
## 6  535.6033 -10.47568   525.1276</code></pre>
<p>We have a final prediction for each respondent. How can we use these models to predict on new data? We follow the same logic. We allow each tree to predict on this new data and then sum the predictions of all the trees.</p>
<p>In case you wanted to build some code that applies our manual proceedure automatically, I have written the code below to do it for you. It fits <span class="math inline">\(N\)</span> models on the same data but after the first model, the dependent variable of the decision tree becomes the residuals of the previous model:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="tree-based-methods.html#cb97-1"></a><span class="co"># This is the base decision tree used in each iteration.</span></span>
<span id="cb97-2"><a href="tree-based-methods.html#cb97-2"></a>dt_tree &lt;-</span>
<span id="cb97-3"><a href="tree-based-methods.html#cb97-3"></a><span class="st">  </span><span class="kw">decision_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">tree_depth =</span> <span class="dv">1</span>, <span class="dt">min_n =</span> <span class="dv">10</span>) <span class="op">%&gt;%</span></span>
<span id="cb97-4"><a href="tree-based-methods.html#cb97-4"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>)</span>
<span id="cb97-5"><a href="tree-based-methods.html#cb97-5"></a></span>
<span id="cb97-6"><a href="tree-based-methods.html#cb97-6"></a><span class="co"># Let&#39;s extract the training data separately to fit the models</span></span>
<span id="cb97-7"><a href="tree-based-methods.html#cb97-7"></a>pisa_tr &lt;-<span class="st"> </span><span class="kw">training</span>(<span class="kw">initial_split</span>(pisa))</span>
<span id="cb97-8"><a href="tree-based-methods.html#cb97-8"></a></span>
<span id="cb97-9"><a href="tree-based-methods.html#cb97-9"></a><span class="co"># Construct our tidyflow</span></span>
<span id="cb97-10"><a href="tree-based-methods.html#cb97-10"></a>tflow &lt;-</span>
<span id="cb97-11"><a href="tree-based-methods.html#cb97-11"></a><span class="st">  </span>pisa_tr <span class="op">%&gt;%</span></span>
<span id="cb97-12"><a href="tree-based-methods.html#cb97-12"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">51231</span>) <span class="op">%&gt;%</span></span>
<span id="cb97-13"><a href="tree-based-methods.html#cb97-13"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>scie_score) <span class="op">%&gt;%</span></span>
<span id="cb97-14"><a href="tree-based-methods.html#cb97-14"></a><span class="st">  </span><span class="kw">plug_model</span>(dt_tree)</span>
<span id="cb97-15"><a href="tree-based-methods.html#cb97-15"></a></span>
<span id="cb97-16"><a href="tree-based-methods.html#cb97-16"></a><span class="co"># How many trees you want to run?</span></span>
<span id="cb97-17"><a href="tree-based-methods.html#cb97-17"></a>n &lt;-<span class="st"> </span><span class="dv">40</span></span>
<span id="cb97-18"><a href="tree-based-methods.html#cb97-18"></a></span>
<span id="cb97-19"><a href="tree-based-methods.html#cb97-19"></a><span class="co"># This list will have the 40 models</span></span>
<span id="cb97-20"><a href="tree-based-methods.html#cb97-20"></a>res &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;list&quot;</span>, n)</span>
<span id="cb97-21"><a href="tree-based-methods.html#cb97-21"></a></span>
<span id="cb97-22"><a href="tree-based-methods.html#cb97-22"></a><span class="co"># This dataframe will have the 40 predictions</span></span>
<span id="cb97-23"><a href="tree-based-methods.html#cb97-23"></a><span class="co"># for each respondent</span></span>
<span id="cb97-24"><a href="tree-based-methods.html#cb97-24"></a>df_pred &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">pred_1 =</span> <span class="kw">rep</span>(<span class="dv">0</span>, <span class="kw">nrow</span>(pisa_tr)))</span>
<span id="cb97-25"><a href="tree-based-methods.html#cb97-25"></a></span>
<span id="cb97-26"><a href="tree-based-methods.html#cb97-26"></a><span class="co"># Fit the first model</span></span>
<span id="cb97-27"><a href="tree-based-methods.html#cb97-27"></a>res[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb97-28"><a href="tree-based-methods.html#cb97-28"></a></span>
<span id="cb97-29"><a href="tree-based-methods.html#cb97-29"></a><span class="co"># Repeat this loop 40-1 times</span></span>
<span id="cb97-30"><a href="tree-based-methods.html#cb97-30"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>(n<span class="dv">-1</span>)) {</span>
<span id="cb97-31"><a href="tree-based-methods.html#cb97-31"></a>  <span class="kw">print</span>(<span class="kw">paste0</span>(<span class="st">&quot;Model &quot;</span>, i))</span>
<span id="cb97-32"><a href="tree-based-methods.html#cb97-32"></a>  <span class="co"># Save the prediction from the last model in `df_pred`</span></span>
<span id="cb97-33"><a href="tree-based-methods.html#cb97-33"></a>  df_pred[[<span class="kw">paste0</span>(<span class="st">&quot;pred_&quot;</span>, i)]] &lt;-<span class="st"> </span><span class="kw">predict</span>(res[[i]],</span>
<span id="cb97-34"><a href="tree-based-methods.html#cb97-34"></a>                                           <span class="dt">new_data =</span> <span class="kw">pull_tflow_rawdata</span>(res[[i]]))[[<span class="dv">1</span>]]</span>
<span id="cb97-35"><a href="tree-based-methods.html#cb97-35"></a></span>
<span id="cb97-36"><a href="tree-based-methods.html#cb97-36"></a>  <span class="co"># Calculate the residuals from the previous model</span></span>
<span id="cb97-37"><a href="tree-based-methods.html#cb97-37"></a>  pred_data &lt;-</span>
<span id="cb97-38"><a href="tree-based-methods.html#cb97-38"></a><span class="st">    </span><span class="kw">cbind</span>(</span>
<span id="cb97-39"><a href="tree-based-methods.html#cb97-39"></a>      <span class="kw">pull_tflow_rawdata</span>(res[[i]]),</span>
<span id="cb97-40"><a href="tree-based-methods.html#cb97-40"></a>      <span class="dt">.pred =</span> df_pred[[<span class="kw">paste0</span>(<span class="st">&quot;pred_&quot;</span>, i)]]</span>
<span id="cb97-41"><a href="tree-based-methods.html#cb97-41"></a>    ) <span class="op">%&gt;%</span></span>
<span id="cb97-42"><a href="tree-based-methods.html#cb97-42"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">math_score =</span> math_score <span class="op">-</span><span class="st"> </span>.pred) <span class="op">%&gt;%</span></span>
<span id="cb97-43"><a href="tree-based-methods.html#cb97-43"></a><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>.pred)</span>
<span id="cb97-44"><a href="tree-based-methods.html#cb97-44"></a></span>
<span id="cb97-45"><a href="tree-based-methods.html#cb97-45"></a>  <span class="co"># Run the actual model with the residuals from the previous</span></span>
<span id="cb97-46"><a href="tree-based-methods.html#cb97-46"></a>  <span class="co"># model</span></span>
<span id="cb97-47"><a href="tree-based-methods.html#cb97-47"></a>  res[[i <span class="op">+</span><span class="st"> </span><span class="dv">1</span>]] &lt;-</span>
<span id="cb97-48"><a href="tree-based-methods.html#cb97-48"></a><span class="st">    </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb97-49"><a href="tree-based-methods.html#cb97-49"></a><span class="st">    </span><span class="kw">replace_data</span>(pred_data) <span class="op">%&gt;%</span></span>
<span id="cb97-50"><a href="tree-based-methods.html#cb97-50"></a><span class="st">    </span><span class="kw">fit</span>()</span>
<span id="cb97-51"><a href="tree-based-methods.html#cb97-51"></a>}</span>
<span id="cb97-52"><a href="tree-based-methods.html#cb97-52"></a></span>
<span id="cb97-53"><a href="tree-based-methods.html#cb97-53"></a><span class="co"># Add up the 40 predictions for each respondent</span></span>
<span id="cb97-54"><a href="tree-based-methods.html#cb97-54"></a><span class="co"># What is the final RMSE?</span></span>
<span id="cb97-55"><a href="tree-based-methods.html#cb97-55"></a>pisa_tr <span class="op">%&gt;%</span></span>
<span id="cb97-56"><a href="tree-based-methods.html#cb97-56"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">.pred =</span> <span class="kw">rowSums</span>(df_pred)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb97-57"><a href="tree-based-methods.html#cb97-57"></a><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></span>
<span id="cb97-58"><a href="tree-based-methods.html#cb97-58"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb97-59"><a href="tree-based-methods.html#cb97-59"></a></span>
<span id="cb97-60"><a href="tree-based-methods.html#cb97-60"></a><span class="co"># Does it match closely the more robust implementation</span></span>
<span id="cb97-61"><a href="tree-based-methods.html#cb97-61"></a><span class="co"># from the package gbm?</span></span>
<span id="cb97-62"><a href="tree-based-methods.html#cb97-62"></a>mod &lt;-<span class="st"> </span>gbm<span class="op">::</span><span class="kw">gbm</span>(math_score <span class="op">~</span><span class="st"> </span>.,</span>
<span id="cb97-63"><a href="tree-based-methods.html#cb97-63"></a>                <span class="dt">data =</span> pisa_tr,</span>
<span id="cb97-64"><a href="tree-based-methods.html#cb97-64"></a>                <span class="dt">n.trees =</span> <span class="dv">40</span>,</span>
<span id="cb97-65"><a href="tree-based-methods.html#cb97-65"></a>                <span class="dt">interaction.depth =</span> <span class="dv">1</span>,</span>
<span id="cb97-66"><a href="tree-based-methods.html#cb97-66"></a>                <span class="dt">n.minobsinnode =</span> <span class="dv">10</span>)</span>
<span id="cb97-67"><a href="tree-based-methods.html#cb97-67"></a>pisa_tr <span class="op">%&gt;%</span></span>
<span id="cb97-68"><a href="tree-based-methods.html#cb97-68"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">.pred2 =</span> <span class="kw">predict</span>(mod, <span class="dt">newdata =</span> pisa_tr, <span class="dt">n.trees =</span> <span class="dv">40</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb97-69"><a href="tree-based-methods.html#cb97-69"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred2)</span></code></pre></div>
<p>This raw implementation of the boosting algorithm is not something you should use for your own research or predictive tasks. Boosting has evolved to be more complex and other features have been introduced. For example, the <code>gbm</code> implementation includes a <code>shrinkage</code> parameter that penalizes each decision tree such that you have to increase the number of trees being fitted. This is a general approach called ‘slow learning’ which usually has better predictive accuracy than our manual approach. There are many other small tweaks that have improved the performance of boosting. We refer the reader to chapter 12 of <span class="citation">Boehmke and Greenwell (<a href="#ref-boehmke2019" role="doc-biblioref">2019</a>)</span> which discusses them in detail.</p>
<p>Let’s fit our trademark model of <code>math_score</code> regressed on all variables with the more advanced implementation of boosting used in the package <code>xgboost</code>. The results from this model can be compared to our previous results of bagging and the random forest:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="tree-based-methods.html#cb98-1"></a>boost_mod &lt;-</span>
<span id="cb98-2"><a href="tree-based-methods.html#cb98-2"></a><span class="st">  </span><span class="kw">boost_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">trees =</span> <span class="dv">500</span>) <span class="op">%&gt;%</span></span>
<span id="cb98-3"><a href="tree-based-methods.html#cb98-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;xgboost&quot;</span>)</span>
<span id="cb98-4"><a href="tree-based-methods.html#cb98-4"></a></span>
<span id="cb98-5"><a href="tree-based-methods.html#cb98-5"></a>tflow &lt;-</span>
<span id="cb98-6"><a href="tree-based-methods.html#cb98-6"></a><span class="st">  </span>pisa <span class="op">%&gt;%</span></span>
<span id="cb98-7"><a href="tree-based-methods.html#cb98-7"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">51231</span>) <span class="op">%&gt;%</span></span>
<span id="cb98-8"><a href="tree-based-methods.html#cb98-8"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>.) <span class="op">%&gt;%</span></span>
<span id="cb98-9"><a href="tree-based-methods.html#cb98-9"></a><span class="st">  </span><span class="kw">plug_split</span>(initial_split) <span class="op">%&gt;%</span></span>
<span id="cb98-10"><a href="tree-based-methods.html#cb98-10"></a><span class="st">  </span><span class="kw">plug_model</span>(boost_mod)</span>
<span id="cb98-11"><a href="tree-based-methods.html#cb98-11"></a></span>
<span id="cb98-12"><a href="tree-based-methods.html#cb98-12"></a>boot_res &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span></code></pre></div>
<pre><code>## [15:14:15] WARNING: amalgamation/../src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="tree-based-methods.html#cb100-1"></a>rmse_gb_train &lt;-</span>
<span id="cb100-2"><a href="tree-based-methods.html#cb100-2"></a><span class="st">  </span>boot_res <span class="op">%&gt;%</span></span>
<span id="cb100-3"><a href="tree-based-methods.html#cb100-3"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb100-4"><a href="tree-based-methods.html#cb100-4"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb100-5"><a href="tree-based-methods.html#cb100-5"></a></span>
<span id="cb100-6"><a href="tree-based-methods.html#cb100-6"></a>rmse_gb_train</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard    0.000630</code></pre>
<p>An <span class="math inline">\(RMSE\)</span> of 0.0006! This an impressive improvement relative to the best random forest or bagging performance. It is even more remarkable that this improvement happens without performing any grid search for the most optimal values in the tuning values.</p>
<p>Let’s check how it performs on the testing data and compare that to the same estimate from the bagged decision trees and the random forest:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="tree-based-methods.html#cb102-1"></a>gb_rmse &lt;-</span>
<span id="cb102-2"><a href="tree-based-methods.html#cb102-2"></a><span class="st">  </span>boot_res <span class="op">%&gt;%</span></span>
<span id="cb102-3"><a href="tree-based-methods.html#cb102-3"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb102-4"><a href="tree-based-methods.html#cb102-4"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred) <span class="op">%&gt;%</span></span>
<span id="cb102-5"><a href="tree-based-methods.html#cb102-5"></a><span class="st">  </span><span class="kw">pull</span>(.estimate)</span>
<span id="cb102-6"><a href="tree-based-methods.html#cb102-6"></a></span>
<span id="cb102-7"><a href="tree-based-methods.html#cb102-7"></a><span class="kw">c</span>(<span class="st">&quot;Bagged decision trees&quot;</span> =<span class="st"> </span>bt_rmse,</span>
<span id="cb102-8"><a href="tree-based-methods.html#cb102-8"></a>  <span class="st">&quot;Random Forest&quot;</span> =<span class="st"> </span>rf_rmse,</span>
<span id="cb102-9"><a href="tree-based-methods.html#cb102-9"></a>  <span class="st">&quot;Extreme Gradient Boosting&quot;</span> =<span class="st"> </span>gb_rmse)</span></code></pre></div>
<pre><code>##     Bagged decision trees             Random Forest Extreme Gradient Boosting 
##                  59.64462                  55.13338                  26.78929</code></pre>
<p>The extreme gradient boosting model achieved a testing error of 26.7892924, considerably lower than the counterpart of the bagged decision trees and the random forest (59.6446197 for the bagged decision trees and 55.1333767 for the random forest, respectively).</p>
<p>Boosting, and it’s more full featured cousin ‘Extreme Gradient Boosting’ (those are the initials of the package <code>xgboost</code>) are considered to be among the best predictive models currently developed. They can achieve impressive predictive power with little tuning and preprocessing of data. However, there is one pitfall that you should be aware of.</p>
<p>In contrast to random forests, increasing the number of trees in a boosting algorithm <strong>can</strong> increase overfitting. For the random forest, increasing the number of trees has no impact on overfitting because what we actually get is the average of all these trees. However, for boosting, increasing the number trees means increasing the number of trees that iteratively try to explain residuals. You might reach a point that adding more trees will just try to explain residuals which are random, resulting in overfitting.</p>
<p><code>boost_tree</code> has implemented a tuning parameter called <code>stop_iter</code> (as of 15th of June 2020, this tuning parameter has now been implemented in the development version of <code>parsnip</code> which you can install with <code>devtools::install_github("tidymodels/parsnip")</code>). <code>stop_iter</code> signals that after <span class="math inline">\(N\)</span> number trees have passed without any improvement, the algorithm should stop. This approach often runs less trees than the user requested.</p>
<p>There are other tuning parameters available in <code>boost_tree</code> which you can use to improve your model. Here I shortly describe each one.</p>
<ul>
<li><p><code>trees</code>: the number of trees that will be ran.</p></li>
<li><p><code>mtry</code>: just as in random forests, <code>mtry</code> can be specified in <code>boost_tree</code> and as expected, it controls the number of variables that will be used at each split of a decision tree.</p></li>
<li><p><code>min_n</code>: controls the minimum number of observations that need to be present in each node of a decision tree. This can avoid having decision trees which overfit a lot.</p></li>
<li><p><code>tree_depth</code>: is the same tuning parameter we used in <code>decision_tree</code> and it controls how complex the tree is allowed to grow. This interacts very strongly with <code>min_n</code>.</p></li>
<li><p><code>learn_rate</code>: controls how much we regularize each tree such that more penalization warrants more decision trees. This is because the algorithm is learning ‘slowly’ and requires more iterations.</p></li>
<li><p><code>loss_reduction</code>: signals the amount of reduction in your loss function (for example, <span class="math inline">\(RMSE\)</span>) that will allow each split in a decision tree to continue to grow. You can see this as cost-effective step: only if the tree improves it’s prediction by <span class="math inline">\(X\)</span>, we allow the tree to produce another split.</p></li>
<li><p><code>sample_size</code>: controls the percentage of the data used in each iteration of the decision tree. This is similar to the bagging approach where we perform bootstraps on each iteration.</p></li>
</ul>
<p>Boosting algorithms have often been considered black boxes in terms of how they work. In this section we manually implemented a very simple boosting algorithm and showed their predictive power with our trademark example.</p>
<p>Note that throughout this entire chapter, all examples and explanations have focused on continuous variables. However, <strong>all</strong> of the techniques discussed above work just as well for dummy variables. We have omitted these discussions because it would be a lot of material for the course.</p>
</div>
<div id="exercises-1" class="section level2">
<h2><span class="header-section-number">3.5</span> Exercises</h2>
<p>In these exercises we’ll continue try to predict the mathematics test score (<code>math_score</code>) from <code>pisa</code>. First, read in the data with:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="tree-based-methods.html#cb104-1"></a>data_link &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/cimentadaj/ml_socsci/master/data/pisa_us_2018.csv&quot;</span></span>
<span id="cb104-2"><a href="tree-based-methods.html#cb104-2"></a>pisa &lt;-<span class="st"> </span><span class="kw">read.csv</span>(data_link)</span></code></pre></div>
<div id="ex1" class="section level4 unnumbered">
<h4>1. Fit a decision tree of <code>math_score</code> on all variables and visualize</h4>
<ul>
<li>Assign a seed of <code>231151</code> to the tidyflow</li>
<li>Separate the data into training/testing with <code>initial_split</code></li>
<li>Fit the <code>decision_tree()</code> with <code>mode = 'regression'</code> but without any arguments (don’t specify <code>min_n</code> or <code>tree_depth</code>)</li>
<li>Extract the final model with <code>pull_tflow_fit</code> and <code>.[['fit']]</code></li>
<li>Visualize the final model with <code>rpart.plot</code></li>
</ul>
<p>Which variables are the most important?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="tree-based-methods.html#cb105-1"></a>tflow &lt;-</span>
<span id="cb105-2"><a href="tree-based-methods.html#cb105-2"></a><span class="st">  </span>pisa <span class="op">%&gt;%</span></span>
<span id="cb105-3"><a href="tree-based-methods.html#cb105-3"></a><span class="st">  </span><span class="kw">tidyflow</span>(<span class="dt">seed =</span> <span class="dv">23151</span>) <span class="op">%&gt;%</span></span>
<span id="cb105-4"><a href="tree-based-methods.html#cb105-4"></a><span class="st">  </span><span class="kw">plug_split</span>(initial_split) <span class="op">%&gt;%</span></span>
<span id="cb105-5"><a href="tree-based-methods.html#cb105-5"></a><span class="st">  </span><span class="kw">plug_formula</span>(math_score <span class="op">~</span><span class="st"> </span>.) <span class="op">%&gt;%</span></span>
<span id="cb105-6"><a href="tree-based-methods.html#cb105-6"></a><span class="st">  </span><span class="kw">plug_model</span>(<span class="kw">decision_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>))</span>
<span id="cb105-7"><a href="tree-based-methods.html#cb105-7"></a></span>
<span id="cb105-8"><a href="tree-based-methods.html#cb105-8"></a>dtree1 &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb105-9"><a href="tree-based-methods.html#cb105-9"></a>dtree1 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span><span class="st"> </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rpart.plot</span>()</span></code></pre></div>
</details>
</div>
<div id="ex2" class="section level4 unnumbered">
<h4>2. Fit the same model from above but excluding the science and literacy test scores</h4>
<ul>
<li>Replace the formula with <code>math_score ~ . - scie_score - read_score</code></li>
<li>Visualize the model with a tree plot</li>
</ul>
<p>Look up the PISA codebook <a href="https://docs.google.com/spreadsheets/d/12--3vD737rcu6olviKutRLEiyKNZ2bynXcJ4CpwtNsQ/edit?usp=sharing">here</a>. Do these variables make sense? Is the ranking of most important variables making sense with respect to <code>math_score</code>?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="tree-based-methods.html#cb106-1"></a>tflow &lt;-</span>
<span id="cb106-2"><a href="tree-based-methods.html#cb106-2"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb106-3"><a href="tree-based-methods.html#cb106-3"></a><span class="st">  </span><span class="kw">replace_formula</span>(math_score <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>scie_score <span class="op">-</span><span class="st"> </span>read_score)</span>
<span id="cb106-4"><a href="tree-based-methods.html#cb106-4"></a></span>
<span id="cb106-5"><a href="tree-based-methods.html#cb106-5"></a>dtree1 &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb106-6"><a href="tree-based-methods.html#cb106-6"></a>dtree1 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span><span class="st"> </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rpart.plot</span>()</span></code></pre></div>
</details>
</div>
<div id="ex3" class="section level4 unnumbered">
<h4>3. Run a grid search of <code>min_n</code> and <code>tree_depth</code> for the single decision tree</h4>
<ul>
<li>Extract the model from the <code>tidyflow</code> with <code>pull_tflow_spec</code> and update <code>min_n</code> and <code>tree_depth</code> to be <code>tune</code></li>
<li>Add a cross-validation step.</li>
<li>Add a <code>grid_regular</code> tuning grid to the model. Be sure to specify the argument <code>levels = 2</code> in <code>plug_grid</code> to force <code>grid_regular</code> to do a grid search of 2 x 2 of the tuning parameters.</li>
<li>Fit the model (this can take a few minutes, that’s why we limited the number of grid values to 2 x 2)</li>
<li>Extract the tuning values with <code>pull_tflow_fit_tuning</code> and summarize which metrics are better with <code>collect_metrics</code></li>
</ul>
<p>Which tuning parameter seems to be more important for a lower <span class="math inline">\(RMSE\)</span>? What is the most optimal combination of tuning parameters?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li><p>It seems that <code>tree_depth</code> is more important because there is no difference between <code>min_n</code> within each <code>tree_depth</code></p></li>
<li><p>Most optimal combination is <code>tree_depth</code> of 15 and <code>min_n</code> of 2, because it’s the simplest model with the lower mean <span class="math inline">\(RMSE\)</span></p></li>
<li><p>Note that this is <strong>probably</strong> not the most optimal decision tree because we are trying very few tuning values (only a 2 x 2 grid). In case you want to experiment with even better models, you can run more tuning values by replacing the <code>levels</code> in <code>plug_grid</code>. If you supply a 10, the model will try a 10 x 10 grid of <code>tree_depth</code> and <code>min_n</code>. Trying out many tuning values is very important because you can visualize whether any particular parameter starts to increase the error rate after a certain threshold.</p></li>
</ul>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="tree-based-methods.html#cb107-1"></a>dectree &lt;-</span>
<span id="cb107-2"><a href="tree-based-methods.html#cb107-2"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb107-3"><a href="tree-based-methods.html#cb107-3"></a><span class="st">  </span><span class="kw">pull_tflow_spec</span>() <span class="op">%&gt;%</span></span>
<span id="cb107-4"><a href="tree-based-methods.html#cb107-4"></a><span class="st">  </span><span class="kw">update</span>(<span class="dt">min_n =</span> <span class="kw">tune</span>(), <span class="dt">tree_depth =</span> <span class="kw">tune</span>())</span>
<span id="cb107-5"><a href="tree-based-methods.html#cb107-5"></a></span>
<span id="cb107-6"><a href="tree-based-methods.html#cb107-6"></a>tflow &lt;-</span>
<span id="cb107-7"><a href="tree-based-methods.html#cb107-7"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb107-8"><a href="tree-based-methods.html#cb107-8"></a><span class="st">  </span><span class="kw">plug_resample</span>(vfold_cv) <span class="op">%&gt;%</span></span>
<span id="cb107-9"><a href="tree-based-methods.html#cb107-9"></a><span class="st">  </span><span class="kw">plug_grid</span>(grid_regular, <span class="dt">levels =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span></span>
<span id="cb107-10"><a href="tree-based-methods.html#cb107-10"></a><span class="st">  </span><span class="kw">replace_model</span>(dectree)</span>
<span id="cb107-11"><a href="tree-based-methods.html#cb107-11"></a></span>
<span id="cb107-12"><a href="tree-based-methods.html#cb107-12"></a>tuned_mod &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb107-13"><a href="tree-based-methods.html#cb107-13"></a></span>
<span id="cb107-14"><a href="tree-based-methods.html#cb107-14"></a>tuned_mod <span class="op">%&gt;%</span></span>
<span id="cb107-15"><a href="tree-based-methods.html#cb107-15"></a><span class="st">  </span><span class="kw">pull_tflow_fit_tuning</span>() <span class="op">%&gt;%</span></span>
<span id="cb107-16"><a href="tree-based-methods.html#cb107-16"></a><span class="st">  </span><span class="kw">collect_metrics</span>() <span class="op">%&gt;%</span></span>
<span id="cb107-17"><a href="tree-based-methods.html#cb107-17"></a><span class="st">  </span><span class="kw">filter</span>(.metric <span class="op">==</span><span class="st"> &quot;rmse&quot;</span>)</span></code></pre></div>
</details>
</div>
<div id="ex4" class="section level4 unnumbered">
<h4>4. Finalize the best model with <code>complete_tflow</code> and predict on the training set</h4>
<ul>
<li><p>Run the best model with <code>complete_tflow</code>. Remember to set the metric from which you will define the best model! Here, we’re focusing on <span class="math inline">\(RMSE\)</span>.</p></li>
<li><p>Use <code>predict_training</code> to predict on the training data and calculate the <span class="math inline">\(RMSE\)</span> with <code>rmse</code></p></li>
</ul>
<p>Compared to the examples in the main sections, is the <span class="math inline">\(RMSE\)</span> acceptable? How could you improve it?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li><p>The <span class="math inline">\(RMSE\)</span> of the model is quite low compared to the main examples. It’s almost twice as large as estimates from the main material.</p></li>
<li><p>We could improve the error rate in many ways. First, we could search for the top 10 or 20 variables and run the model only using those. That way we can a get much simpler model and check whethere it gives very similar results. Additionally, we can try many more tuning values with the <code>levels</code> argument of <code>plug_grid</code>. Further stratigies could explore whether certain variables need to be recoded to capture meaningful variation or whether some variables need transformations.</p></li>
</ul>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="tree-based-methods.html#cb108-1"></a>final_dtree &lt;-<span class="st"> </span>tuned_mod <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">complete_tflow</span>(<span class="dt">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span>
<span id="cb108-2"><a href="tree-based-methods.html#cb108-2"></a></span>
<span id="cb108-3"><a href="tree-based-methods.html#cb108-3"></a><span class="co"># You can check that it uses the best combination by pulling out</span></span>
<span id="cb108-4"><a href="tree-based-methods.html#cb108-4"></a><span class="co"># the model:</span></span>
<span id="cb108-5"><a href="tree-based-methods.html#cb108-5"></a>final_dtree <span class="op">%&gt;%</span></span>
<span id="cb108-6"><a href="tree-based-methods.html#cb108-6"></a><span class="st">  </span><span class="kw">pull_tflow_spec</span>()</span>
<span id="cb108-7"><a href="tree-based-methods.html#cb108-7"></a></span>
<span id="cb108-8"><a href="tree-based-methods.html#cb108-8"></a>final_dtree <span class="op">%&gt;%</span></span>
<span id="cb108-9"><a href="tree-based-methods.html#cb108-9"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb108-10"><a href="tree-based-methods.html#cb108-10"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
</details>
</div>
<div id="ex5" class="section level4 unnumbered">
<h4>5. Run the same model for bagged decision trees</h4>
<ul>
<li>Remove the resample and grid with <code>drop_resample</code> and <code>drop_grid</code></li>
<li>Replace the model with a <code>bag_tree</code> model instead of the single <code>decision_tree</code></li>
<li>Fit the bagged decision tree</li>
<li>Pull out the fitted model with <code>pull_tflow_fit</code> and explore the top ten variables</li>
<li>Calculate the <span class="math inline">\(RMSE\)</span> on the training data</li>
</ul>
<p>Which are the most important variables? Do they correspond with the variables used in the decision tree? Is the <span class="math inline">\(RMSE\)</span> lower than the decision tree exercise?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li><p>If the top variables don’t make substantive sense, they might just be capturing noise in the data. It’s always important to keep a critical eye on your models. Check whether the variables chosen by the model make sense. If they don’t, explore through visualization and correlations whether they are indeed related to the test score and how.</p></li>
<li><p>Often, a model with only the most important variables does as well as a model with 500 variables.</p></li>
</ul>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="tree-based-methods.html#cb109-1"></a>tflow &lt;-</span>
<span id="cb109-2"><a href="tree-based-methods.html#cb109-2"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb109-3"><a href="tree-based-methods.html#cb109-3"></a><span class="st">  </span><span class="kw">drop_resample</span>() <span class="op">%&gt;%</span></span>
<span id="cb109-4"><a href="tree-based-methods.html#cb109-4"></a><span class="st">  </span><span class="kw">drop_grid</span>() <span class="op">%&gt;%</span></span>
<span id="cb109-5"><a href="tree-based-methods.html#cb109-5"></a><span class="st">  </span><span class="kw">replace_model</span>(<span class="kw">bag_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>))</span>
<span id="cb109-6"><a href="tree-based-methods.html#cb109-6"></a></span>
<span id="cb109-7"><a href="tree-based-methods.html#cb109-7"></a>btree_mod &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb109-8"><a href="tree-based-methods.html#cb109-8"></a></span>
<span id="cb109-9"><a href="tree-based-methods.html#cb109-9"></a><span class="co"># Explore the top ten variables</span></span>
<span id="cb109-10"><a href="tree-based-methods.html#cb109-10"></a>btree_mod <span class="op">%&gt;%</span></span>
<span id="cb109-11"><a href="tree-based-methods.html#cb109-11"></a><span class="st">  </span><span class="kw">pull_tflow_fit</span>()</span>
<span id="cb109-12"><a href="tree-based-methods.html#cb109-12"></a></span>
<span id="cb109-13"><a href="tree-based-methods.html#cb109-13"></a><span class="co"># RMSE of the bagged decision tree</span></span>
<span id="cb109-14"><a href="tree-based-methods.html#cb109-14"></a>btree_mod <span class="op">%&gt;%</span></span>
<span id="cb109-15"><a href="tree-based-methods.html#cb109-15"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb109-16"><a href="tree-based-methods.html#cb109-16"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
</details>
</div>
<div id="ex6" class="section level4 unnumbered">
<h4>6. Run the same model from above but only on the ten top variables from the previous model</h4>
<ul>
<li>Identify the top 10 variables from the model</li>
<li>Replace the original formula with the summarized formula with only the top ten variables</li>
<li>Extract the model from the <code>tidyflow</code> with <code>pull_tflow_spec</code> and <code>set_engine</code> with <code>times = 100</code> to increase the bootstraps to 100. Remember, the higher the number of bootstraps, the more robust the model is.</li>
<li>Replace the old <code>bag_tree</code> from the <code>tidyflow</code> with this new model with <code>times = 100</code>.</li>
<li>Fit the model</li>
<li>Calculate the <span class="math inline">\(RMSE\)</span> of the model</li>
</ul>
<p>How far is the <span class="math inline">\(RMSE\)</span> of ‘optimized’ model from the previous model? Is it worth chosing this model over the other one? Why didn’t we run <code>times = 100</code> for the previous model?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li><p>This model’s <span class="math inline">\(RMSE\)</span> is 26.3 while the one with 500 variables is 24. Depending on your context, you might prefer either one. For example, in a business setting, an improvement of 2 points might increase revenue by a big margin. In other settings, the difference of 2 points might not be that important in substantive terms, and thus a simple model would be better. For this case, a difference of 2 points in a math test score is very small and probably within the margin of error of the models. The best decision here is to keep the simplest model.</p></li>
<li><p>Running 100 models with 500 variables is very time consuming. We decided to use <code>times = 100</code> on the simplified model because the time spent on fitting is really fast and allows us to rapidly prototype different models.</p></li>
</ul>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="tree-based-methods.html#cb110-1"></a><span class="co"># Which are the top ten variables?</span></span>
<span id="cb110-2"><a href="tree-based-methods.html#cb110-2"></a>btree_mod <span class="op">%&gt;%</span></span>
<span id="cb110-3"><a href="tree-based-methods.html#cb110-3"></a><span class="st">  </span><span class="kw">pull_tflow_fit</span>()</span>
<span id="cb110-4"><a href="tree-based-methods.html#cb110-4"></a></span>
<span id="cb110-5"><a href="tree-based-methods.html#cb110-5"></a>optim_btree &lt;-</span>
<span id="cb110-6"><a href="tree-based-methods.html#cb110-6"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb110-7"><a href="tree-based-methods.html#cb110-7"></a><span class="st">  </span><span class="kw">pull_tflow_spec</span>() <span class="op">%&gt;%</span></span>
<span id="cb110-8"><a href="tree-based-methods.html#cb110-8"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;rpart&quot;</span>, <span class="dt">times =</span> <span class="dv">100</span>)</span>
<span id="cb110-9"><a href="tree-based-methods.html#cb110-9"></a></span>
<span id="cb110-10"><a href="tree-based-methods.html#cb110-10"></a><span class="co"># Replace the formula with 500 variables with only the top 10</span></span>
<span id="cb110-11"><a href="tree-based-methods.html#cb110-11"></a>tflow &lt;-</span>
<span id="cb110-12"><a href="tree-based-methods.html#cb110-12"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb110-13"><a href="tree-based-methods.html#cb110-13"></a><span class="st">  </span><span class="kw">replace_formula</span>(math_score <span class="op">~</span><span class="st"> </span>ST166Q03HA <span class="op">+</span><span class="st"> </span>METASPAM <span class="op">+</span><span class="st"> </span>PISADIFF <span class="op">+</span><span class="st"> </span>ST166Q01HA <span class="op">+</span><span class="st"> </span>ESCS <span class="op">+</span><span class="st"> </span>ST163Q03HA <span class="op">+</span><span class="st"> </span>ST166Q04HA <span class="op">+</span><span class="st"> </span>ST163Q02HA <span class="op">+</span><span class="st"> </span>ST163Q04HA <span class="op">+</span><span class="st"> </span>HISEI) <span class="op">%&gt;%</span></span>
<span id="cb110-14"><a href="tree-based-methods.html#cb110-14"></a><span class="st">  </span><span class="kw">replace_model</span>(optim_btree)</span>
<span id="cb110-15"><a href="tree-based-methods.html#cb110-15"></a></span>
<span id="cb110-16"><a href="tree-based-methods.html#cb110-16"></a>topten_mod &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb110-17"><a href="tree-based-methods.html#cb110-17"></a></span>
<span id="cb110-18"><a href="tree-based-methods.html#cb110-18"></a>topten_mod <span class="op">%&gt;%</span></span>
<span id="cb110-19"><a href="tree-based-methods.html#cb110-19"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb110-20"><a href="tree-based-methods.html#cb110-20"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
</details>
</div>
<div id="ex7" class="section level4 unnumbered">
<h4>7. Perform a grid search on the simplified model of 10 variables</h4>
<ul>
<li>Extract the model from the <code>tidyflow</code> and update <code>min_n</code> and <code>tree_depth</code> to be <code>tune</code>. If you want the models to run faster, change <code>times = 20</code> with <code>set_engine</code> to this model.</li>
<li>Replace the model the old model with the tuned one in the <code>tidyflow</code></li>
<li>Add a cross-validation step to the <code>tidyflow</code> with <code>vfold_cv</code></li>
<li>Plug in a manual grid with <code>expand.grid</code>. Set <code>min_n</code> to explore the values <code>c(5, 10)</code> and <code>tree_depth</code> to explore the values <code>c(3, 9)</code>.</li>
<li>Fit the model to perform the grid search (this might take a few minutes since we’re running 200 models, 20 bootstraps by 10 cross-validation datasets)</li>
<li>Pull the tuning results with <code>pull_tflow_fit_tuning</code> and pass it to <code>collect_metrics</code>. Explore the <span class="math inline">\(RMSE\)</span> of the best tuning values</li>
<li>Train the best model with <code>complete_tflow</code>, <code>predict_training</code> and calculate the best <span class="math inline">\(RMSE\)</span> with <code>rmse</code>.</li>
</ul>
<p>Is the value of the <span class="math inline">\(RMSE\)</span> lower than the previous model? Why? Does it make sense to do a grid search? Are the results improving?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li>For certain scenarios, performing a grid search of the most optimal tuning values might not a good idea with bagged decision trees. Why? Because the purpose of bagged trees is to run small trees that overfit the data as much as possible. That is, they allow the tree depth to grow as much as possible and require as little as 2 observations with each node. This means that there is really no improvement for choosing more ‘adequate’ tuning values. In the end, each small tree should be as complex as possible because what we’re really after is the average prediction of all these small trees.</li>
</ul>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="tree-based-methods.html#cb111-1"></a>tune_btree_mod &lt;-</span>
<span id="cb111-2"><a href="tree-based-methods.html#cb111-2"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb111-3"><a href="tree-based-methods.html#cb111-3"></a><span class="st">  </span><span class="kw">pull_tflow_spec</span>() <span class="op">%&gt;%</span></span>
<span id="cb111-4"><a href="tree-based-methods.html#cb111-4"></a><span class="st">  </span><span class="kw">update</span>(<span class="dt">min_n =</span> <span class="kw">tune</span>(), <span class="dt">tree_depth =</span> <span class="kw">tune</span>()) <span class="op">%&gt;%</span></span>
<span id="cb111-5"><a href="tree-based-methods.html#cb111-5"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="dt">times =</span> <span class="dv">20</span>, <span class="st">&quot;rpart&quot;</span>)</span>
<span id="cb111-6"><a href="tree-based-methods.html#cb111-6"></a></span>
<span id="cb111-7"><a href="tree-based-methods.html#cb111-7"></a>tflow &lt;-</span>
<span id="cb111-8"><a href="tree-based-methods.html#cb111-8"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb111-9"><a href="tree-based-methods.html#cb111-9"></a><span class="st">  </span><span class="kw">plug_resample</span>(vfold_cv) <span class="op">%&gt;%</span></span>
<span id="cb111-10"><a href="tree-based-methods.html#cb111-10"></a><span class="st">  </span><span class="kw">plug_grid</span>(expand.grid, <span class="dt">min_n =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">10</span>), <span class="dt">tree_depth =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">9</span>)) <span class="op">%&gt;%</span></span>
<span id="cb111-11"><a href="tree-based-methods.html#cb111-11"></a><span class="st">  </span><span class="kw">replace_model</span>(tune_btree_mod)</span>
<span id="cb111-12"><a href="tree-based-methods.html#cb111-12"></a></span>
<span id="cb111-13"><a href="tree-based-methods.html#cb111-13"></a>tuned_btree &lt;-<span class="st"> </span><span class="kw">fit</span>(tflow)</span>
<span id="cb111-14"><a href="tree-based-methods.html#cb111-14"></a></span>
<span id="cb111-15"><a href="tree-based-methods.html#cb111-15"></a>tuned_btree <span class="op">%&gt;%</span></span>
<span id="cb111-16"><a href="tree-based-methods.html#cb111-16"></a><span class="st">  </span><span class="kw">pull_tflow_fit_tuning</span>() <span class="op">%&gt;%</span></span>
<span id="cb111-17"><a href="tree-based-methods.html#cb111-17"></a><span class="st">  </span><span class="kw">collect_metrics</span>() <span class="op">%&gt;%</span></span>
<span id="cb111-18"><a href="tree-based-methods.html#cb111-18"></a><span class="st">  </span><span class="kw">filter</span>(.metric <span class="op">==</span><span class="st"> &quot;rmse&quot;</span>)</span>
<span id="cb111-19"><a href="tree-based-methods.html#cb111-19"></a></span>
<span id="cb111-20"><a href="tree-based-methods.html#cb111-20"></a>final_btree &lt;-<span class="st"> </span>tuned_btree <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">complete_tflow</span>(<span class="dt">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span>
<span id="cb111-21"><a href="tree-based-methods.html#cb111-21"></a></span>
<span id="cb111-22"><a href="tree-based-methods.html#cb111-22"></a>final_btree <span class="op">%&gt;%</span></span>
<span id="cb111-23"><a href="tree-based-methods.html#cb111-23"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb111-24"><a href="tree-based-methods.html#cb111-24"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
</details>
</div>
<div id="ex8" class="section level4 unnumbered">
<h4>8. Fit an untuned random forest to check whether the default values are enough to beat the other models</h4>
<p>Random Forests are well known for achieving greater predictive performance than bagging with simple off-the-shelf tuning values. That is without any grid search, they can often perform well with the default values. Run two models, one with the same specification as before (with the top ten variables) and one regressed on all the variables in the data sets and compare the <span class="math inline">\(RMSE\)</span> of the models.</p>
<ul>
<li>Define a <code>rand_forest</code> model with 500 trees and replace the previous model form the <code>tflow</code>. Remember to set <code>importance = "impurity"</code> in the engine to check for the most important variables.</li>
<li>Since we won’t be doing any grid search, remove the resample and grid from the <code>tflow</code></li>
<li>Create another <code>tidyflow</code> (with the same specification) but replacing the formula with <code>math_score ~ . - scie_score - read_score</code></li>
<li>Fit both <code>tflow</code></li>
<li>Calculate the <span class="math inline">\(RMSE\)</span> in the training set for both models</li>
<li>Do the most important variables from the more complex models match the top 10 variables from the simple model?</li>
</ul>
<p>Does the random forest beat the previous model in accuracy? Does the simple model perform better than the more complex one?</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li>Without any grid search, the random forest beats the previous models by a range of nearly 20 math points.
<ul>
<li>The more complex model seems to outperform the simple model by around 14 points.</li>
<li>Nearly all variables from the top 10 are also present in the random forest, however the performance increase is notable so the remaining variables must be contributing to a certain extent.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="tree-based-methods.html#cb112-1"></a>rand_mod &lt;-</span>
<span id="cb112-2"><a href="tree-based-methods.html#cb112-2"></a><span class="st">  </span><span class="kw">rand_forest</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">trees =</span> <span class="dv">500</span>) <span class="op">%&gt;%</span></span>
<span id="cb112-3"><a href="tree-based-methods.html#cb112-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>, <span class="dt">importance =</span> <span class="st">&quot;impurity&quot;</span>)</span>
<span id="cb112-4"><a href="tree-based-methods.html#cb112-4"></a></span>
<span id="cb112-5"><a href="tree-based-methods.html#cb112-5"></a>tflow &lt;-</span>
<span id="cb112-6"><a href="tree-based-methods.html#cb112-6"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb112-7"><a href="tree-based-methods.html#cb112-7"></a><span class="st">  </span><span class="kw">replace_model</span>(rand_mod) <span class="op">%&gt;%</span></span>
<span id="cb112-8"><a href="tree-based-methods.html#cb112-8"></a><span class="st">  </span><span class="kw">drop_resample</span>() <span class="op">%&gt;%</span></span>
<span id="cb112-9"><a href="tree-based-methods.html#cb112-9"></a><span class="st">  </span><span class="kw">drop_grid</span>()</span>
<span id="cb112-10"><a href="tree-based-methods.html#cb112-10"></a></span>
<span id="cb112-11"><a href="tree-based-methods.html#cb112-11"></a>tflow_all &lt;-</span>
<span id="cb112-12"><a href="tree-based-methods.html#cb112-12"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb112-13"><a href="tree-based-methods.html#cb112-13"></a><span class="st">  </span><span class="kw">replace_formula</span>(math_score <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>scie_score <span class="op">-</span><span class="st"> </span>read_score)</span>
<span id="cb112-14"><a href="tree-based-methods.html#cb112-14"></a></span>
<span id="cb112-15"><a href="tree-based-methods.html#cb112-15"></a>res_randf &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb112-16"><a href="tree-based-methods.html#cb112-16"></a>res_randf_all &lt;-<span class="st"> </span>tflow_all <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb112-17"><a href="tree-based-methods.html#cb112-17"></a></span>
<span id="cb112-18"><a href="tree-based-methods.html#cb112-18"></a><span class="co"># RMSE of simple model</span></span>
<span id="cb112-19"><a href="tree-based-methods.html#cb112-19"></a>res_randf <span class="op">%&gt;%</span></span>
<span id="cb112-20"><a href="tree-based-methods.html#cb112-20"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb112-21"><a href="tree-based-methods.html#cb112-21"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb112-22"><a href="tree-based-methods.html#cb112-22"></a></span>
<span id="cb112-23"><a href="tree-based-methods.html#cb112-23"></a><span class="co"># RMSE of complex model</span></span>
<span id="cb112-24"><a href="tree-based-methods.html#cb112-24"></a>res_randf_all <span class="op">%&gt;%</span></span>
<span id="cb112-25"><a href="tree-based-methods.html#cb112-25"></a><span class="st">  </span><span class="kw">predict_training</span>() <span class="op">%&gt;%</span></span>
<span id="cb112-26"><a href="tree-based-methods.html#cb112-26"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span>
<span id="cb112-27"><a href="tree-based-methods.html#cb112-27"></a></span>
<span id="cb112-28"><a href="tree-based-methods.html#cb112-28"></a><span class="co"># Visualize the top 10 variables</span></span>
<span id="cb112-29"><a href="tree-based-methods.html#cb112-29"></a>res_randf_all <span class="op">%&gt;%</span></span>
<span id="cb112-30"><a href="tree-based-methods.html#cb112-30"></a><span class="st">  </span><span class="kw">pull_tflow_fit</span>() <span class="op">%&gt;%</span></span>
<span id="cb112-31"><a href="tree-based-methods.html#cb112-31"></a><span class="st">  </span>.[[<span class="st">&#39;fit&#39;</span>]] <span class="op">%&gt;%</span></span>
<span id="cb112-32"><a href="tree-based-methods.html#cb112-32"></a><span class="st">  </span><span class="kw">vip</span>() <span class="op">+</span></span>
<span id="cb112-33"><a href="tree-based-methods.html#cb112-33"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
</details>
</div>
<div id="ex9" class="section level4 unnumbered">
<h4>9. Perform a grid search using a boosting algorithm</h4>
<p>From the example in the main text, we saw that boosting had the highest accuracy out of all models. However, can we improve it? This exercise is exploratory. Try running a <code>boost_tree</code> varying levels of <code>trees</code> and <code>learn_rate</code>.</p>
<p>Keep in mind that:</p>
<ul>
<li>Increasing the number of trees can results in greater overfitting</li>
<li>If the learning rate is decreased, it means that the model is learning slower and thus greater trees are needed</li>
</ul>
<p>The testing error for the default boosting algorithm was <code>54</code>. Can you improve that? One strategy would be to perform a grid search. Another strategy is to focus on variables which are important for predicting <code>math_score</code>.</p>
<details>
<p><summary><strong>&gt; Answer </strong></summary></p>
<ul>
<li>Here we settled for a solution which increased the number of trees from 500 to 1000 but decreased the default learning rate of 0.3 to 0.1. This difference decreased the testing error to 48 points, 7 points below the benchmark.</li>
</ul>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="tree-based-methods.html#cb113-1"></a>xg_mod &lt;-</span>
<span id="cb113-2"><a href="tree-based-methods.html#cb113-2"></a><span class="st">  </span><span class="kw">boost_tree</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>, <span class="dt">trees =</span> <span class="dv">1000</span>, <span class="dt">learn_rate =</span> <span class="fl">0.1</span>) <span class="op">%&gt;%</span></span>
<span id="cb113-3"><a href="tree-based-methods.html#cb113-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;xgboost&quot;</span>, <span class="dt">importance =</span> <span class="st">&quot;impurity&quot;</span>)</span>
<span id="cb113-4"><a href="tree-based-methods.html#cb113-4"></a></span>
<span id="cb113-5"><a href="tree-based-methods.html#cb113-5"></a>tflow &lt;-</span>
<span id="cb113-6"><a href="tree-based-methods.html#cb113-6"></a><span class="st">  </span>tflow <span class="op">%&gt;%</span></span>
<span id="cb113-7"><a href="tree-based-methods.html#cb113-7"></a><span class="st">  </span><span class="kw">replace_model</span>(xg_mod) <span class="op">%&gt;%</span></span>
<span id="cb113-8"><a href="tree-based-methods.html#cb113-8"></a><span class="st">  </span><span class="kw">replace_formula</span>(math_score <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>scie_score <span class="op">-</span><span class="st"> </span>read_score)</span>
<span id="cb113-9"><a href="tree-based-methods.html#cb113-9"></a></span>
<span id="cb113-10"><a href="tree-based-methods.html#cb113-10"></a>res_boosting &lt;-<span class="st"> </span>tflow <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">fit</span>()</span>
<span id="cb113-11"><a href="tree-based-methods.html#cb113-11"></a></span>
<span id="cb113-12"><a href="tree-based-methods.html#cb113-12"></a>res_boosting <span class="op">%&gt;%</span></span>
<span id="cb113-13"><a href="tree-based-methods.html#cb113-13"></a><span class="st">  </span><span class="kw">predict_testing</span>() <span class="op">%&gt;%</span></span>
<span id="cb113-14"><a href="tree-based-methods.html#cb113-14"></a><span class="st">  </span><span class="kw">rmse</span>(math_score, .pred)</span></code></pre></div>
</details>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-boehmke2019">
<p>Boehmke, Brad, and Brandon M Greenwell. 2019. <em>Hands-on Machine Learning with R</em>. CRC Press.</p>
</div>
<div id="ref-james2013">
<p>James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013. <em>An Introduction to Statistical Learning</em>. Vol. 112. Springer.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regularization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="loss-functions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
